/*
InvoicePDFs

Testing NumberingSequencesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package invoicepdfs

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID/invoicepdfs"
)

func Test_invoicepdfs_NumberingSequencesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test NumberingSequencesAPIService ConsumeNextApiV1NumberingSequencesSequenceIdNextPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sequenceId string

		resp, httpRes, err := apiClient.NumberingSequencesAPI.ConsumeNextApiV1NumberingSequencesSequenceIdNextPost(context.Background(), sequenceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NumberingSequencesAPIService CreateSequenceApiV1NumberingSequencesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.NumberingSequencesAPI.CreateSequenceApiV1NumberingSequencesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NumberingSequencesAPIService DeleteSequenceApiV1NumberingSequencesSequenceIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sequenceId string

		resp, httpRes, err := apiClient.NumberingSequencesAPI.DeleteSequenceApiV1NumberingSequencesSequenceIdDelete(context.Background(), sequenceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NumberingSequencesAPIService GetSequenceApiV1NumberingSequencesSequenceIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sequenceId string

		resp, httpRes, err := apiClient.NumberingSequencesAPI.GetSequenceApiV1NumberingSequencesSequenceIdGet(context.Background(), sequenceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NumberingSequencesAPIService ListSequencesApiV1NumberingSequencesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.NumberingSequencesAPI.ListSequencesApiV1NumberingSequencesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NumberingSequencesAPIService PreviewSequenceApiV1NumberingSequencesSequenceIdPreviewPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sequenceId string

		resp, httpRes, err := apiClient.NumberingSequencesAPI.PreviewSequenceApiV1NumberingSequencesSequenceIdPreviewPost(context.Background(), sequenceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NumberingSequencesAPIService UpdateSequenceApiV1NumberingSequencesSequenceIdPatch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sequenceId string

		resp, httpRes, err := apiClient.NumberingSequencesAPI.UpdateSequenceApiV1NumberingSequencesSequenceIdPatch(context.Background(), sequenceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
