/*
InvoicePDFs

Testing RendersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package invoicepdfs

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/invoicepdfs/invoicepdfs-go"
)

func Test_invoicepdfs_RendersAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RendersAPIService DownloadRender", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var renderId string

		resp, httpRes, err := apiClient.RendersAPI.DownloadRender(context.Background(), renderId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RendersAPIService GetRender", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var renderId string

		resp, httpRes, err := apiClient.RendersAPI.GetRender(context.Background(), renderId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
