/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RenderFailureOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RenderFailureOut{}

// RenderFailureOut Why a render failed, in the same shape the synchronous path returns.  A synchronous render of a document EN 16931 would reject answers `422 compliance_failed` with every violation at once — a list of fields to go and fill in. A queued render has to be able to say the same thing: the caller who chose `async` did not choose a worse answer.
type RenderFailureOut struct {
	// `compliance_failed` for a document that is well-formed and would be rejected by the ruleset it asked for; `unprocessable_entity` for one the renderer could not make sense of. The same codes the synchronous path returns.
	Code string `json:"code"`
	Message string `json:"message"`
	Details map[string]interface{} `json:"details,omitempty"`
}

type _RenderFailureOut RenderFailureOut

// NewRenderFailureOut instantiates a new RenderFailureOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRenderFailureOut(code string, message string) *RenderFailureOut {
	this := RenderFailureOut{}
	this.Code = code
	this.Message = message
	return &this
}

// NewRenderFailureOutWithDefaults instantiates a new RenderFailureOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRenderFailureOutWithDefaults() *RenderFailureOut {
	this := RenderFailureOut{}
	return &this
}

// GetCode returns the Code field value
func (o *RenderFailureOut) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *RenderFailureOut) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *RenderFailureOut) SetCode(v string) {
	o.Code = v
}

// GetMessage returns the Message field value
func (o *RenderFailureOut) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *RenderFailureOut) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *RenderFailureOut) SetMessage(v string) {
	o.Message = v
}

// GetDetails returns the Details field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RenderFailureOut) GetDetails() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RenderFailureOut) GetDetailsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Details) {
		return map[string]interface{}{}, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *RenderFailureOut) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given map[string]interface{} and assigns it to the Details field.
func (o *RenderFailureOut) SetDetails(v map[string]interface{}) {
	o.Details = v
}

func (o RenderFailureOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RenderFailureOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["message"] = o.Message
	if o.Details != nil {
		toSerialize["details"] = o.Details
	}
	return toSerialize, nil
}

func (o *RenderFailureOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRenderFailureOut := _RenderFailureOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRenderFailureOut)

	if err != nil {
		return err
	}

	*o = RenderFailureOut(varRenderFailureOut)

	return err
}

type NullableRenderFailureOut struct {
	value *RenderFailureOut
	isSet bool
}

func (v NullableRenderFailureOut) Get() *RenderFailureOut {
	return v.value
}

func (v *NullableRenderFailureOut) Set(val *RenderFailureOut) {
	v.value = val
	v.isSet = true
}

func (v NullableRenderFailureOut) IsSet() bool {
	return v.isSet
}

func (v *NullableRenderFailureOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRenderFailureOut(val *RenderFailureOut) *NullableRenderFailureOut {
	return &NullableRenderFailureOut{value: val, isSet: true}
}

func (v NullableRenderFailureOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRenderFailureOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


