/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RecurringInvoiceOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecurringInvoiceOut{}

// RecurringInvoiceOut struct for RecurringInvoiceOut
type RecurringInvoiceOut struct {
	Id string `json:"id"`
	Status string `json:"status"`
	BusinessProfileId string `json:"business_profile_id"`
	CustomerId string `json:"customer_id"`
	Frequency string `json:"frequency"`
	Interval int32 `json:"interval"`
	NextOccurrenceDate NullableString `json:"next_occurrence_date"`
	EndDate NullableString `json:"end_date"`
	OccurrencesCreated int32 `json:"occurrences_created"`
	MaxOccurrences NullableInt32 `json:"max_occurrences"`
	NumberingSequenceId NullableString `json:"numbering_sequence_id"`
	AutoFinalize bool `json:"auto_finalize"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type _RecurringInvoiceOut RecurringInvoiceOut

// NewRecurringInvoiceOut instantiates a new RecurringInvoiceOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecurringInvoiceOut(id string, status string, businessProfileId string, customerId string, frequency string, interval int32, nextOccurrenceDate NullableString, endDate NullableString, occurrencesCreated int32, maxOccurrences NullableInt32, numberingSequenceId NullableString, autoFinalize bool, createdAt string, updatedAt string) *RecurringInvoiceOut {
	this := RecurringInvoiceOut{}
	this.Id = id
	this.Status = status
	this.BusinessProfileId = businessProfileId
	this.CustomerId = customerId
	this.Frequency = frequency
	this.Interval = interval
	this.NextOccurrenceDate = nextOccurrenceDate
	this.EndDate = endDate
	this.OccurrencesCreated = occurrencesCreated
	this.MaxOccurrences = maxOccurrences
	this.NumberingSequenceId = numberingSequenceId
	this.AutoFinalize = autoFinalize
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewRecurringInvoiceOutWithDefaults instantiates a new RecurringInvoiceOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecurringInvoiceOutWithDefaults() *RecurringInvoiceOut {
	this := RecurringInvoiceOut{}
	return &this
}

// GetId returns the Id field value
func (o *RecurringInvoiceOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RecurringInvoiceOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RecurringInvoiceOut) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *RecurringInvoiceOut) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *RecurringInvoiceOut) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *RecurringInvoiceOut) SetStatus(v string) {
	o.Status = v
}

// GetBusinessProfileId returns the BusinessProfileId field value
func (o *RecurringInvoiceOut) GetBusinessProfileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BusinessProfileId
}

// GetBusinessProfileIdOk returns a tuple with the BusinessProfileId field value
// and a boolean to check if the value has been set.
func (o *RecurringInvoiceOut) GetBusinessProfileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BusinessProfileId, true
}

// SetBusinessProfileId sets field value
func (o *RecurringInvoiceOut) SetBusinessProfileId(v string) {
	o.BusinessProfileId = v
}

// GetCustomerId returns the CustomerId field value
func (o *RecurringInvoiceOut) GetCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *RecurringInvoiceOut) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *RecurringInvoiceOut) SetCustomerId(v string) {
	o.CustomerId = v
}

// GetFrequency returns the Frequency field value
func (o *RecurringInvoiceOut) GetFrequency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value
// and a boolean to check if the value has been set.
func (o *RecurringInvoiceOut) GetFrequencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Frequency, true
}

// SetFrequency sets field value
func (o *RecurringInvoiceOut) SetFrequency(v string) {
	o.Frequency = v
}

// GetInterval returns the Interval field value
func (o *RecurringInvoiceOut) GetInterval() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Interval
}

// GetIntervalOk returns a tuple with the Interval field value
// and a boolean to check if the value has been set.
func (o *RecurringInvoiceOut) GetIntervalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Interval, true
}

// SetInterval sets field value
func (o *RecurringInvoiceOut) SetInterval(v int32) {
	o.Interval = v
}

// GetNextOccurrenceDate returns the NextOccurrenceDate field value
// If the value is explicit nil, the zero value for string will be returned
func (o *RecurringInvoiceOut) GetNextOccurrenceDate() string {
	if o == nil || o.NextOccurrenceDate.Get() == nil {
		var ret string
		return ret
	}

	return *o.NextOccurrenceDate.Get()
}

// GetNextOccurrenceDateOk returns a tuple with the NextOccurrenceDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecurringInvoiceOut) GetNextOccurrenceDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextOccurrenceDate.Get(), o.NextOccurrenceDate.IsSet()
}

// SetNextOccurrenceDate sets field value
func (o *RecurringInvoiceOut) SetNextOccurrenceDate(v string) {
	o.NextOccurrenceDate.Set(&v)
}

// GetEndDate returns the EndDate field value
// If the value is explicit nil, the zero value for string will be returned
func (o *RecurringInvoiceOut) GetEndDate() string {
	if o == nil || o.EndDate.Get() == nil {
		var ret string
		return ret
	}

	return *o.EndDate.Get()
}

// GetEndDateOk returns a tuple with the EndDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecurringInvoiceOut) GetEndDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndDate.Get(), o.EndDate.IsSet()
}

// SetEndDate sets field value
func (o *RecurringInvoiceOut) SetEndDate(v string) {
	o.EndDate.Set(&v)
}

// GetOccurrencesCreated returns the OccurrencesCreated field value
func (o *RecurringInvoiceOut) GetOccurrencesCreated() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OccurrencesCreated
}

// GetOccurrencesCreatedOk returns a tuple with the OccurrencesCreated field value
// and a boolean to check if the value has been set.
func (o *RecurringInvoiceOut) GetOccurrencesCreatedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OccurrencesCreated, true
}

// SetOccurrencesCreated sets field value
func (o *RecurringInvoiceOut) SetOccurrencesCreated(v int32) {
	o.OccurrencesCreated = v
}

// GetMaxOccurrences returns the MaxOccurrences field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *RecurringInvoiceOut) GetMaxOccurrences() int32 {
	if o == nil || o.MaxOccurrences.Get() == nil {
		var ret int32
		return ret
	}

	return *o.MaxOccurrences.Get()
}

// GetMaxOccurrencesOk returns a tuple with the MaxOccurrences field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecurringInvoiceOut) GetMaxOccurrencesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxOccurrences.Get(), o.MaxOccurrences.IsSet()
}

// SetMaxOccurrences sets field value
func (o *RecurringInvoiceOut) SetMaxOccurrences(v int32) {
	o.MaxOccurrences.Set(&v)
}

// GetNumberingSequenceId returns the NumberingSequenceId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *RecurringInvoiceOut) GetNumberingSequenceId() string {
	if o == nil || o.NumberingSequenceId.Get() == nil {
		var ret string
		return ret
	}

	return *o.NumberingSequenceId.Get()
}

// GetNumberingSequenceIdOk returns a tuple with the NumberingSequenceId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecurringInvoiceOut) GetNumberingSequenceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NumberingSequenceId.Get(), o.NumberingSequenceId.IsSet()
}

// SetNumberingSequenceId sets field value
func (o *RecurringInvoiceOut) SetNumberingSequenceId(v string) {
	o.NumberingSequenceId.Set(&v)
}

// GetAutoFinalize returns the AutoFinalize field value
func (o *RecurringInvoiceOut) GetAutoFinalize() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AutoFinalize
}

// GetAutoFinalizeOk returns a tuple with the AutoFinalize field value
// and a boolean to check if the value has been set.
func (o *RecurringInvoiceOut) GetAutoFinalizeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AutoFinalize, true
}

// SetAutoFinalize sets field value
func (o *RecurringInvoiceOut) SetAutoFinalize(v bool) {
	o.AutoFinalize = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *RecurringInvoiceOut) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *RecurringInvoiceOut) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *RecurringInvoiceOut) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *RecurringInvoiceOut) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *RecurringInvoiceOut) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *RecurringInvoiceOut) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o RecurringInvoiceOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecurringInvoiceOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["business_profile_id"] = o.BusinessProfileId
	toSerialize["customer_id"] = o.CustomerId
	toSerialize["frequency"] = o.Frequency
	toSerialize["interval"] = o.Interval
	toSerialize["next_occurrence_date"] = o.NextOccurrenceDate.Get()
	toSerialize["end_date"] = o.EndDate.Get()
	toSerialize["occurrences_created"] = o.OccurrencesCreated
	toSerialize["max_occurrences"] = o.MaxOccurrences.Get()
	toSerialize["numbering_sequence_id"] = o.NumberingSequenceId.Get()
	toSerialize["auto_finalize"] = o.AutoFinalize
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *RecurringInvoiceOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"business_profile_id",
		"customer_id",
		"frequency",
		"interval",
		"next_occurrence_date",
		"end_date",
		"occurrences_created",
		"max_occurrences",
		"numbering_sequence_id",
		"auto_finalize",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecurringInvoiceOut := _RecurringInvoiceOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecurringInvoiceOut)

	if err != nil {
		return err
	}

	*o = RecurringInvoiceOut(varRecurringInvoiceOut)

	return err
}

type NullableRecurringInvoiceOut struct {
	value *RecurringInvoiceOut
	isSet bool
}

func (v NullableRecurringInvoiceOut) Get() *RecurringInvoiceOut {
	return v.value
}

func (v *NullableRecurringInvoiceOut) Set(val *RecurringInvoiceOut) {
	v.value = val
	v.isSet = true
}

func (v NullableRecurringInvoiceOut) IsSet() bool {
	return v.isSet
}

func (v *NullableRecurringInvoiceOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecurringInvoiceOut(val *RecurringInvoiceOut) *NullableRecurringInvoiceOut {
	return &NullableRecurringInvoiceOut{value: val, isSet: true}
}

func (v NullableRecurringInvoiceOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecurringInvoiceOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


