/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the PaymentCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentCreateRequest{}

// PaymentCreateRequest struct for PaymentCreateRequest
type PaymentCreateRequest struct {
	Amount string `json:"amount"`
	PaidAt time.Time `json:"paid_at"`
	Method NullableString `json:"method,omitempty"`
	Reference NullableString `json:"reference,omitempty"`
	Notes NullableString `json:"notes,omitempty"`
}

type _PaymentCreateRequest PaymentCreateRequest

// NewPaymentCreateRequest instantiates a new PaymentCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentCreateRequest(amount string, paidAt time.Time) *PaymentCreateRequest {
	this := PaymentCreateRequest{}
	this.Amount = amount
	this.PaidAt = paidAt
	return &this
}

// NewPaymentCreateRequestWithDefaults instantiates a new PaymentCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentCreateRequestWithDefaults() *PaymentCreateRequest {
	this := PaymentCreateRequest{}
	return &this
}

// GetAmount returns the Amount field value
func (o *PaymentCreateRequest) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *PaymentCreateRequest) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *PaymentCreateRequest) SetAmount(v string) {
	o.Amount = v
}

// GetPaidAt returns the PaidAt field value
func (o *PaymentCreateRequest) GetPaidAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.PaidAt
}

// GetPaidAtOk returns a tuple with the PaidAt field value
// and a boolean to check if the value has been set.
func (o *PaymentCreateRequest) GetPaidAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaidAt, true
}

// SetPaidAt sets field value
func (o *PaymentCreateRequest) SetPaidAt(v time.Time) {
	o.PaidAt = v
}

// GetMethod returns the Method field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentCreateRequest) GetMethod() string {
	if o == nil || IsNil(o.Method.Get()) {
		var ret string
		return ret
	}
	return *o.Method.Get()
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentCreateRequest) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Method.Get(), o.Method.IsSet()
}

// HasMethod returns a boolean if a field has been set.
func (o *PaymentCreateRequest) HasMethod() bool {
	if o != nil && o.Method.IsSet() {
		return true
	}

	return false
}

// SetMethod gets a reference to the given NullableString and assigns it to the Method field.
func (o *PaymentCreateRequest) SetMethod(v string) {
	o.Method.Set(&v)
}
// SetMethodNil sets the value for Method to be an explicit nil
func (o *PaymentCreateRequest) SetMethodNil() {
	o.Method.Set(nil)
}

// UnsetMethod ensures that no value is present for Method, not even an explicit nil
func (o *PaymentCreateRequest) UnsetMethod() {
	o.Method.Unset()
}

// GetReference returns the Reference field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentCreateRequest) GetReference() string {
	if o == nil || IsNil(o.Reference.Get()) {
		var ret string
		return ret
	}
	return *o.Reference.Get()
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentCreateRequest) GetReferenceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reference.Get(), o.Reference.IsSet()
}

// HasReference returns a boolean if a field has been set.
func (o *PaymentCreateRequest) HasReference() bool {
	if o != nil && o.Reference.IsSet() {
		return true
	}

	return false
}

// SetReference gets a reference to the given NullableString and assigns it to the Reference field.
func (o *PaymentCreateRequest) SetReference(v string) {
	o.Reference.Set(&v)
}
// SetReferenceNil sets the value for Reference to be an explicit nil
func (o *PaymentCreateRequest) SetReferenceNil() {
	o.Reference.Set(nil)
}

// UnsetReference ensures that no value is present for Reference, not even an explicit nil
func (o *PaymentCreateRequest) UnsetReference() {
	o.Reference.Unset()
}

// GetNotes returns the Notes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaymentCreateRequest) GetNotes() string {
	if o == nil || IsNil(o.Notes.Get()) {
		var ret string
		return ret
	}
	return *o.Notes.Get()
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentCreateRequest) GetNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Notes.Get(), o.Notes.IsSet()
}

// HasNotes returns a boolean if a field has been set.
func (o *PaymentCreateRequest) HasNotes() bool {
	if o != nil && o.Notes.IsSet() {
		return true
	}

	return false
}

// SetNotes gets a reference to the given NullableString and assigns it to the Notes field.
func (o *PaymentCreateRequest) SetNotes(v string) {
	o.Notes.Set(&v)
}
// SetNotesNil sets the value for Notes to be an explicit nil
func (o *PaymentCreateRequest) SetNotesNil() {
	o.Notes.Set(nil)
}

// UnsetNotes ensures that no value is present for Notes, not even an explicit nil
func (o *PaymentCreateRequest) UnsetNotes() {
	o.Notes.Unset()
}

func (o PaymentCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount"] = o.Amount
	toSerialize["paid_at"] = o.PaidAt
	if o.Method.IsSet() {
		toSerialize["method"] = o.Method.Get()
	}
	if o.Reference.IsSet() {
		toSerialize["reference"] = o.Reference.Get()
	}
	if o.Notes.IsSet() {
		toSerialize["notes"] = o.Notes.Get()
	}
	return toSerialize, nil
}

func (o *PaymentCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount",
		"paid_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentCreateRequest := _PaymentCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaymentCreateRequest)

	if err != nil {
		return err
	}

	*o = PaymentCreateRequest(varPaymentCreateRequest)

	return err
}

type NullablePaymentCreateRequest struct {
	value *PaymentCreateRequest
	isSet bool
}

func (v NullablePaymentCreateRequest) Get() *PaymentCreateRequest {
	return v.value
}

func (v *NullablePaymentCreateRequest) Set(val *PaymentCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentCreateRequest(val *PaymentCreateRequest) *NullablePaymentCreateRequest {
	return &NullablePaymentCreateRequest{value: val, isSet: true}
}

func (v NullablePaymentCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


