/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MoneyOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MoneyOut{}

// MoneyOut struct for MoneyOut
type MoneyOut struct {
	Amount string `json:"amount"`
	Currency string `json:"currency"`
}

type _MoneyOut MoneyOut

// NewMoneyOut instantiates a new MoneyOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMoneyOut(amount string, currency string) *MoneyOut {
	this := MoneyOut{}
	this.Amount = amount
	this.Currency = currency
	return &this
}

// NewMoneyOutWithDefaults instantiates a new MoneyOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMoneyOutWithDefaults() *MoneyOut {
	this := MoneyOut{}
	return &this
}

// GetAmount returns the Amount field value
func (o *MoneyOut) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *MoneyOut) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *MoneyOut) SetAmount(v string) {
	o.Amount = v
}

// GetCurrency returns the Currency field value
func (o *MoneyOut) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *MoneyOut) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *MoneyOut) SetCurrency(v string) {
	o.Currency = v
}

func (o MoneyOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MoneyOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount"] = o.Amount
	toSerialize["currency"] = o.Currency
	return toSerialize, nil
}

func (o *MoneyOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount",
		"currency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMoneyOut := _MoneyOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMoneyOut)

	if err != nil {
		return err
	}

	*o = MoneyOut(varMoneyOut)

	return err
}

type NullableMoneyOut struct {
	value *MoneyOut
	isSet bool
}

func (v NullableMoneyOut) Get() *MoneyOut {
	return v.value
}

func (v *NullableMoneyOut) Set(val *MoneyOut) {
	v.value = val
	v.isSet = true
}

func (v NullableMoneyOut) IsSet() bool {
	return v.isSet
}

func (v *NullableMoneyOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMoneyOut(val *MoneyOut) *NullableMoneyOut {
	return &NullableMoneyOut{value: val, isSet: true}
}

func (v NullableMoneyOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMoneyOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


