/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TaxCategory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaxCategory{}

// TaxCategory How a tax is treated, as opposed to what it is called.  `name` and `rate` do not say this: two taxes at 0% may be zero-rated, exempt, reverse-charge or outside scope, and EN 16931 keeps them in separate VAT breakdown groups with different mandatory fields. Optional, so an invoice that never mentions a category calculates exactly as before.
type TaxCategory struct {
	// UNCL5305 tax category code — S standard, Z zero-rated, E exempt, AE reverse charge, K intra-community, G export, O outside scope
	Code string `json:"code"`
	ExemptionReason NullableString `json:"exemption_reason,omitempty"`
	ExemptionReasonCode NullableString `json:"exemption_reason_code,omitempty"`
}

type _TaxCategory TaxCategory

// NewTaxCategory instantiates a new TaxCategory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaxCategory(code string) *TaxCategory {
	this := TaxCategory{}
	this.Code = code
	return &this
}

// NewTaxCategoryWithDefaults instantiates a new TaxCategory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaxCategoryWithDefaults() *TaxCategory {
	this := TaxCategory{}
	return &this
}

// GetCode returns the Code field value
func (o *TaxCategory) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *TaxCategory) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *TaxCategory) SetCode(v string) {
	o.Code = v
}

// GetExemptionReason returns the ExemptionReason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TaxCategory) GetExemptionReason() string {
	if o == nil || IsNil(o.ExemptionReason.Get()) {
		var ret string
		return ret
	}
	return *o.ExemptionReason.Get()
}

// GetExemptionReasonOk returns a tuple with the ExemptionReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaxCategory) GetExemptionReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExemptionReason.Get(), o.ExemptionReason.IsSet()
}

// HasExemptionReason returns a boolean if a field has been set.
func (o *TaxCategory) HasExemptionReason() bool {
	if o != nil && o.ExemptionReason.IsSet() {
		return true
	}

	return false
}

// SetExemptionReason gets a reference to the given NullableString and assigns it to the ExemptionReason field.
func (o *TaxCategory) SetExemptionReason(v string) {
	o.ExemptionReason.Set(&v)
}
// SetExemptionReasonNil sets the value for ExemptionReason to be an explicit nil
func (o *TaxCategory) SetExemptionReasonNil() {
	o.ExemptionReason.Set(nil)
}

// UnsetExemptionReason ensures that no value is present for ExemptionReason, not even an explicit nil
func (o *TaxCategory) UnsetExemptionReason() {
	o.ExemptionReason.Unset()
}

// GetExemptionReasonCode returns the ExemptionReasonCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TaxCategory) GetExemptionReasonCode() string {
	if o == nil || IsNil(o.ExemptionReasonCode.Get()) {
		var ret string
		return ret
	}
	return *o.ExemptionReasonCode.Get()
}

// GetExemptionReasonCodeOk returns a tuple with the ExemptionReasonCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaxCategory) GetExemptionReasonCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExemptionReasonCode.Get(), o.ExemptionReasonCode.IsSet()
}

// HasExemptionReasonCode returns a boolean if a field has been set.
func (o *TaxCategory) HasExemptionReasonCode() bool {
	if o != nil && o.ExemptionReasonCode.IsSet() {
		return true
	}

	return false
}

// SetExemptionReasonCode gets a reference to the given NullableString and assigns it to the ExemptionReasonCode field.
func (o *TaxCategory) SetExemptionReasonCode(v string) {
	o.ExemptionReasonCode.Set(&v)
}
// SetExemptionReasonCodeNil sets the value for ExemptionReasonCode to be an explicit nil
func (o *TaxCategory) SetExemptionReasonCodeNil() {
	o.ExemptionReasonCode.Set(nil)
}

// UnsetExemptionReasonCode ensures that no value is present for ExemptionReasonCode, not even an explicit nil
func (o *TaxCategory) UnsetExemptionReasonCode() {
	o.ExemptionReasonCode.Unset()
}

func (o TaxCategory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaxCategory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if o.ExemptionReason.IsSet() {
		toSerialize["exemption_reason"] = o.ExemptionReason.Get()
	}
	if o.ExemptionReasonCode.IsSet() {
		toSerialize["exemption_reason_code"] = o.ExemptionReasonCode.Get()
	}
	return toSerialize, nil
}

func (o *TaxCategory) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTaxCategory := _TaxCategory{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTaxCategory)

	if err != nil {
		return err
	}

	*o = TaxCategory(varTaxCategory)

	return err
}

type NullableTaxCategory struct {
	value *TaxCategory
	isSet bool
}

func (v NullableTaxCategory) Get() *TaxCategory {
	return v.value
}

func (v *NullableTaxCategory) Set(val *TaxCategory) {
	v.value = val
	v.isSet = true
}

func (v NullableTaxCategory) IsSet() bool {
	return v.isSet
}

func (v *NullableTaxCategory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaxCategory(val *TaxCategory) *NullableTaxCategory {
	return &NullableTaxCategory{value: val, isSet: true}
}

func (v NullableTaxCategory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaxCategory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


