/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DocumentCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentCreateRequest{}

// DocumentCreateRequest struct for DocumentCreateRequest
type DocumentCreateRequest struct {
	DocumentType *string `json:"document_type,omitempty"`
	Number string `json:"number"`
	IssueDate string `json:"issue_date"`
	DueDate NullableString `json:"due_date,omitempty"`
	Currency string `json:"currency"`
	Locale NullableString `json:"locale,omitempty"`
	BusinessProfileId string `json:"business_profile_id"`
	CustomerId string `json:"customer_id"`
	SourceDocumentId NullableString `json:"source_document_id,omitempty"`
	Reason NullableString `json:"reason,omitempty"`
	ShipTo NullablePostalAddress `json:"ship_to,omitempty"`
	LineItems []StandardLineItemInput `json:"line_items"`
	Discounts []LineItemDiscountInput `json:"discounts,omitempty"`
	Shipping NullableInvoiceShippingInput `json:"shipping,omitempty"`
	Notes []InvoiceNoteInput `json:"notes,omitempty"`
	Terms []InvoiceTermInput `json:"terms,omitempty"`
	CustomFields []InvoiceCustomFieldInput `json:"custom_fields,omitempty"`
	Payment NullableInvoicePaymentInput `json:"payment,omitempty"`
	Branding NullableInvoiceBrandingInput `json:"branding,omitempty"`
	BrandingProfileId NullableString `json:"branding_profile_id,omitempty"`
}

type _DocumentCreateRequest DocumentCreateRequest

// NewDocumentCreateRequest instantiates a new DocumentCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentCreateRequest(number string, issueDate string, currency string, businessProfileId string, customerId string, lineItems []StandardLineItemInput) *DocumentCreateRequest {
	this := DocumentCreateRequest{}
	var documentType string = "invoice"
	this.DocumentType = &documentType
	this.Number = number
	this.IssueDate = issueDate
	this.Currency = currency
	this.BusinessProfileId = businessProfileId
	this.CustomerId = customerId
	this.LineItems = lineItems
	return &this
}

// NewDocumentCreateRequestWithDefaults instantiates a new DocumentCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentCreateRequestWithDefaults() *DocumentCreateRequest {
	this := DocumentCreateRequest{}
	var documentType string = "invoice"
	this.DocumentType = &documentType
	return &this
}

// GetDocumentType returns the DocumentType field value if set, zero value otherwise.
func (o *DocumentCreateRequest) GetDocumentType() string {
	if o == nil || IsNil(o.DocumentType) {
		var ret string
		return ret
	}
	return *o.DocumentType
}

// GetDocumentTypeOk returns a tuple with the DocumentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentCreateRequest) GetDocumentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DocumentType) {
		return nil, false
	}
	return o.DocumentType, true
}

// HasDocumentType returns a boolean if a field has been set.
func (o *DocumentCreateRequest) HasDocumentType() bool {
	if o != nil && !IsNil(o.DocumentType) {
		return true
	}

	return false
}

// SetDocumentType gets a reference to the given string and assigns it to the DocumentType field.
func (o *DocumentCreateRequest) SetDocumentType(v string) {
	o.DocumentType = &v
}

// GetNumber returns the Number field value
func (o *DocumentCreateRequest) GetNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Number
}

// GetNumberOk returns a tuple with the Number field value
// and a boolean to check if the value has been set.
func (o *DocumentCreateRequest) GetNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Number, true
}

// SetNumber sets field value
func (o *DocumentCreateRequest) SetNumber(v string) {
	o.Number = v
}

// GetIssueDate returns the IssueDate field value
func (o *DocumentCreateRequest) GetIssueDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IssueDate
}

// GetIssueDateOk returns a tuple with the IssueDate field value
// and a boolean to check if the value has been set.
func (o *DocumentCreateRequest) GetIssueDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IssueDate, true
}

// SetIssueDate sets field value
func (o *DocumentCreateRequest) SetIssueDate(v string) {
	o.IssueDate = v
}

// GetDueDate returns the DueDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DocumentCreateRequest) GetDueDate() string {
	if o == nil || IsNil(o.DueDate.Get()) {
		var ret string
		return ret
	}
	return *o.DueDate.Get()
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DocumentCreateRequest) GetDueDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DueDate.Get(), o.DueDate.IsSet()
}

// HasDueDate returns a boolean if a field has been set.
func (o *DocumentCreateRequest) HasDueDate() bool {
	if o != nil && o.DueDate.IsSet() {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given NullableString and assigns it to the DueDate field.
func (o *DocumentCreateRequest) SetDueDate(v string) {
	o.DueDate.Set(&v)
}
// SetDueDateNil sets the value for DueDate to be an explicit nil
func (o *DocumentCreateRequest) SetDueDateNil() {
	o.DueDate.Set(nil)
}

// UnsetDueDate ensures that no value is present for DueDate, not even an explicit nil
func (o *DocumentCreateRequest) UnsetDueDate() {
	o.DueDate.Unset()
}

// GetCurrency returns the Currency field value
func (o *DocumentCreateRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *DocumentCreateRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *DocumentCreateRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetLocale returns the Locale field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DocumentCreateRequest) GetLocale() string {
	if o == nil || IsNil(o.Locale.Get()) {
		var ret string
		return ret
	}
	return *o.Locale.Get()
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DocumentCreateRequest) GetLocaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Locale.Get(), o.Locale.IsSet()
}

// HasLocale returns a boolean if a field has been set.
func (o *DocumentCreateRequest) HasLocale() bool {
	if o != nil && o.Locale.IsSet() {
		return true
	}

	return false
}

// SetLocale gets a reference to the given NullableString and assigns it to the Locale field.
func (o *DocumentCreateRequest) SetLocale(v string) {
	o.Locale.Set(&v)
}
// SetLocaleNil sets the value for Locale to be an explicit nil
func (o *DocumentCreateRequest) SetLocaleNil() {
	o.Locale.Set(nil)
}

// UnsetLocale ensures that no value is present for Locale, not even an explicit nil
func (o *DocumentCreateRequest) UnsetLocale() {
	o.Locale.Unset()
}

// GetBusinessProfileId returns the BusinessProfileId field value
func (o *DocumentCreateRequest) GetBusinessProfileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BusinessProfileId
}

// GetBusinessProfileIdOk returns a tuple with the BusinessProfileId field value
// and a boolean to check if the value has been set.
func (o *DocumentCreateRequest) GetBusinessProfileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BusinessProfileId, true
}

// SetBusinessProfileId sets field value
func (o *DocumentCreateRequest) SetBusinessProfileId(v string) {
	o.BusinessProfileId = v
}

// GetCustomerId returns the CustomerId field value
func (o *DocumentCreateRequest) GetCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *DocumentCreateRequest) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *DocumentCreateRequest) SetCustomerId(v string) {
	o.CustomerId = v
}

// GetSourceDocumentId returns the SourceDocumentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DocumentCreateRequest) GetSourceDocumentId() string {
	if o == nil || IsNil(o.SourceDocumentId.Get()) {
		var ret string
		return ret
	}
	return *o.SourceDocumentId.Get()
}

// GetSourceDocumentIdOk returns a tuple with the SourceDocumentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DocumentCreateRequest) GetSourceDocumentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceDocumentId.Get(), o.SourceDocumentId.IsSet()
}

// HasSourceDocumentId returns a boolean if a field has been set.
func (o *DocumentCreateRequest) HasSourceDocumentId() bool {
	if o != nil && o.SourceDocumentId.IsSet() {
		return true
	}

	return false
}

// SetSourceDocumentId gets a reference to the given NullableString and assigns it to the SourceDocumentId field.
func (o *DocumentCreateRequest) SetSourceDocumentId(v string) {
	o.SourceDocumentId.Set(&v)
}
// SetSourceDocumentIdNil sets the value for SourceDocumentId to be an explicit nil
func (o *DocumentCreateRequest) SetSourceDocumentIdNil() {
	o.SourceDocumentId.Set(nil)
}

// UnsetSourceDocumentId ensures that no value is present for SourceDocumentId, not even an explicit nil
func (o *DocumentCreateRequest) UnsetSourceDocumentId() {
	o.SourceDocumentId.Unset()
}

// GetReason returns the Reason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DocumentCreateRequest) GetReason() string {
	if o == nil || IsNil(o.Reason.Get()) {
		var ret string
		return ret
	}
	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DocumentCreateRequest) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// HasReason returns a boolean if a field has been set.
func (o *DocumentCreateRequest) HasReason() bool {
	if o != nil && o.Reason.IsSet() {
		return true
	}

	return false
}

// SetReason gets a reference to the given NullableString and assigns it to the Reason field.
func (o *DocumentCreateRequest) SetReason(v string) {
	o.Reason.Set(&v)
}
// SetReasonNil sets the value for Reason to be an explicit nil
func (o *DocumentCreateRequest) SetReasonNil() {
	o.Reason.Set(nil)
}

// UnsetReason ensures that no value is present for Reason, not even an explicit nil
func (o *DocumentCreateRequest) UnsetReason() {
	o.Reason.Unset()
}

// GetShipTo returns the ShipTo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DocumentCreateRequest) GetShipTo() PostalAddress {
	if o == nil || IsNil(o.ShipTo.Get()) {
		var ret PostalAddress
		return ret
	}
	return *o.ShipTo.Get()
}

// GetShipToOk returns a tuple with the ShipTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DocumentCreateRequest) GetShipToOk() (*PostalAddress, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShipTo.Get(), o.ShipTo.IsSet()
}

// HasShipTo returns a boolean if a field has been set.
func (o *DocumentCreateRequest) HasShipTo() bool {
	if o != nil && o.ShipTo.IsSet() {
		return true
	}

	return false
}

// SetShipTo gets a reference to the given NullablePostalAddress and assigns it to the ShipTo field.
func (o *DocumentCreateRequest) SetShipTo(v PostalAddress) {
	o.ShipTo.Set(&v)
}
// SetShipToNil sets the value for ShipTo to be an explicit nil
func (o *DocumentCreateRequest) SetShipToNil() {
	o.ShipTo.Set(nil)
}

// UnsetShipTo ensures that no value is present for ShipTo, not even an explicit nil
func (o *DocumentCreateRequest) UnsetShipTo() {
	o.ShipTo.Unset()
}

// GetLineItems returns the LineItems field value
func (o *DocumentCreateRequest) GetLineItems() []StandardLineItemInput {
	if o == nil {
		var ret []StandardLineItemInput
		return ret
	}

	return o.LineItems
}

// GetLineItemsOk returns a tuple with the LineItems field value
// and a boolean to check if the value has been set.
func (o *DocumentCreateRequest) GetLineItemsOk() ([]StandardLineItemInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.LineItems, true
}

// SetLineItems sets field value
func (o *DocumentCreateRequest) SetLineItems(v []StandardLineItemInput) {
	o.LineItems = v
}

// GetDiscounts returns the Discounts field value if set, zero value otherwise.
func (o *DocumentCreateRequest) GetDiscounts() []LineItemDiscountInput {
	if o == nil || IsNil(o.Discounts) {
		var ret []LineItemDiscountInput
		return ret
	}
	return o.Discounts
}

// GetDiscountsOk returns a tuple with the Discounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentCreateRequest) GetDiscountsOk() ([]LineItemDiscountInput, bool) {
	if o == nil || IsNil(o.Discounts) {
		return nil, false
	}
	return o.Discounts, true
}

// HasDiscounts returns a boolean if a field has been set.
func (o *DocumentCreateRequest) HasDiscounts() bool {
	if o != nil && !IsNil(o.Discounts) {
		return true
	}

	return false
}

// SetDiscounts gets a reference to the given []LineItemDiscountInput and assigns it to the Discounts field.
func (o *DocumentCreateRequest) SetDiscounts(v []LineItemDiscountInput) {
	o.Discounts = v
}

// GetShipping returns the Shipping field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DocumentCreateRequest) GetShipping() InvoiceShippingInput {
	if o == nil || IsNil(o.Shipping.Get()) {
		var ret InvoiceShippingInput
		return ret
	}
	return *o.Shipping.Get()
}

// GetShippingOk returns a tuple with the Shipping field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DocumentCreateRequest) GetShippingOk() (*InvoiceShippingInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Shipping.Get(), o.Shipping.IsSet()
}

// HasShipping returns a boolean if a field has been set.
func (o *DocumentCreateRequest) HasShipping() bool {
	if o != nil && o.Shipping.IsSet() {
		return true
	}

	return false
}

// SetShipping gets a reference to the given NullableInvoiceShippingInput and assigns it to the Shipping field.
func (o *DocumentCreateRequest) SetShipping(v InvoiceShippingInput) {
	o.Shipping.Set(&v)
}
// SetShippingNil sets the value for Shipping to be an explicit nil
func (o *DocumentCreateRequest) SetShippingNil() {
	o.Shipping.Set(nil)
}

// UnsetShipping ensures that no value is present for Shipping, not even an explicit nil
func (o *DocumentCreateRequest) UnsetShipping() {
	o.Shipping.Unset()
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *DocumentCreateRequest) GetNotes() []InvoiceNoteInput {
	if o == nil || IsNil(o.Notes) {
		var ret []InvoiceNoteInput
		return ret
	}
	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentCreateRequest) GetNotesOk() ([]InvoiceNoteInput, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *DocumentCreateRequest) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given []InvoiceNoteInput and assigns it to the Notes field.
func (o *DocumentCreateRequest) SetNotes(v []InvoiceNoteInput) {
	o.Notes = v
}

// GetTerms returns the Terms field value if set, zero value otherwise.
func (o *DocumentCreateRequest) GetTerms() []InvoiceTermInput {
	if o == nil || IsNil(o.Terms) {
		var ret []InvoiceTermInput
		return ret
	}
	return o.Terms
}

// GetTermsOk returns a tuple with the Terms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentCreateRequest) GetTermsOk() ([]InvoiceTermInput, bool) {
	if o == nil || IsNil(o.Terms) {
		return nil, false
	}
	return o.Terms, true
}

// HasTerms returns a boolean if a field has been set.
func (o *DocumentCreateRequest) HasTerms() bool {
	if o != nil && !IsNil(o.Terms) {
		return true
	}

	return false
}

// SetTerms gets a reference to the given []InvoiceTermInput and assigns it to the Terms field.
func (o *DocumentCreateRequest) SetTerms(v []InvoiceTermInput) {
	o.Terms = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *DocumentCreateRequest) GetCustomFields() []InvoiceCustomFieldInput {
	if o == nil || IsNil(o.CustomFields) {
		var ret []InvoiceCustomFieldInput
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentCreateRequest) GetCustomFieldsOk() ([]InvoiceCustomFieldInput, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return nil, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *DocumentCreateRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given []InvoiceCustomFieldInput and assigns it to the CustomFields field.
func (o *DocumentCreateRequest) SetCustomFields(v []InvoiceCustomFieldInput) {
	o.CustomFields = v
}

// GetPayment returns the Payment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DocumentCreateRequest) GetPayment() InvoicePaymentInput {
	if o == nil || IsNil(o.Payment.Get()) {
		var ret InvoicePaymentInput
		return ret
	}
	return *o.Payment.Get()
}

// GetPaymentOk returns a tuple with the Payment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DocumentCreateRequest) GetPaymentOk() (*InvoicePaymentInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Payment.Get(), o.Payment.IsSet()
}

// HasPayment returns a boolean if a field has been set.
func (o *DocumentCreateRequest) HasPayment() bool {
	if o != nil && o.Payment.IsSet() {
		return true
	}

	return false
}

// SetPayment gets a reference to the given NullableInvoicePaymentInput and assigns it to the Payment field.
func (o *DocumentCreateRequest) SetPayment(v InvoicePaymentInput) {
	o.Payment.Set(&v)
}
// SetPaymentNil sets the value for Payment to be an explicit nil
func (o *DocumentCreateRequest) SetPaymentNil() {
	o.Payment.Set(nil)
}

// UnsetPayment ensures that no value is present for Payment, not even an explicit nil
func (o *DocumentCreateRequest) UnsetPayment() {
	o.Payment.Unset()
}

// GetBranding returns the Branding field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DocumentCreateRequest) GetBranding() InvoiceBrandingInput {
	if o == nil || IsNil(o.Branding.Get()) {
		var ret InvoiceBrandingInput
		return ret
	}
	return *o.Branding.Get()
}

// GetBrandingOk returns a tuple with the Branding field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DocumentCreateRequest) GetBrandingOk() (*InvoiceBrandingInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Branding.Get(), o.Branding.IsSet()
}

// HasBranding returns a boolean if a field has been set.
func (o *DocumentCreateRequest) HasBranding() bool {
	if o != nil && o.Branding.IsSet() {
		return true
	}

	return false
}

// SetBranding gets a reference to the given NullableInvoiceBrandingInput and assigns it to the Branding field.
func (o *DocumentCreateRequest) SetBranding(v InvoiceBrandingInput) {
	o.Branding.Set(&v)
}
// SetBrandingNil sets the value for Branding to be an explicit nil
func (o *DocumentCreateRequest) SetBrandingNil() {
	o.Branding.Set(nil)
}

// UnsetBranding ensures that no value is present for Branding, not even an explicit nil
func (o *DocumentCreateRequest) UnsetBranding() {
	o.Branding.Unset()
}

// GetBrandingProfileId returns the BrandingProfileId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DocumentCreateRequest) GetBrandingProfileId() string {
	if o == nil || IsNil(o.BrandingProfileId.Get()) {
		var ret string
		return ret
	}
	return *o.BrandingProfileId.Get()
}

// GetBrandingProfileIdOk returns a tuple with the BrandingProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DocumentCreateRequest) GetBrandingProfileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BrandingProfileId.Get(), o.BrandingProfileId.IsSet()
}

// HasBrandingProfileId returns a boolean if a field has been set.
func (o *DocumentCreateRequest) HasBrandingProfileId() bool {
	if o != nil && o.BrandingProfileId.IsSet() {
		return true
	}

	return false
}

// SetBrandingProfileId gets a reference to the given NullableString and assigns it to the BrandingProfileId field.
func (o *DocumentCreateRequest) SetBrandingProfileId(v string) {
	o.BrandingProfileId.Set(&v)
}
// SetBrandingProfileIdNil sets the value for BrandingProfileId to be an explicit nil
func (o *DocumentCreateRequest) SetBrandingProfileIdNil() {
	o.BrandingProfileId.Set(nil)
}

// UnsetBrandingProfileId ensures that no value is present for BrandingProfileId, not even an explicit nil
func (o *DocumentCreateRequest) UnsetBrandingProfileId() {
	o.BrandingProfileId.Unset()
}

func (o DocumentCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DocumentType) {
		toSerialize["document_type"] = o.DocumentType
	}
	toSerialize["number"] = o.Number
	toSerialize["issue_date"] = o.IssueDate
	if o.DueDate.IsSet() {
		toSerialize["due_date"] = o.DueDate.Get()
	}
	toSerialize["currency"] = o.Currency
	if o.Locale.IsSet() {
		toSerialize["locale"] = o.Locale.Get()
	}
	toSerialize["business_profile_id"] = o.BusinessProfileId
	toSerialize["customer_id"] = o.CustomerId
	if o.SourceDocumentId.IsSet() {
		toSerialize["source_document_id"] = o.SourceDocumentId.Get()
	}
	if o.Reason.IsSet() {
		toSerialize["reason"] = o.Reason.Get()
	}
	if o.ShipTo.IsSet() {
		toSerialize["ship_to"] = o.ShipTo.Get()
	}
	toSerialize["line_items"] = o.LineItems
	if !IsNil(o.Discounts) {
		toSerialize["discounts"] = o.Discounts
	}
	if o.Shipping.IsSet() {
		toSerialize["shipping"] = o.Shipping.Get()
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.Terms) {
		toSerialize["terms"] = o.Terms
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}
	if o.Payment.IsSet() {
		toSerialize["payment"] = o.Payment.Get()
	}
	if o.Branding.IsSet() {
		toSerialize["branding"] = o.Branding.Get()
	}
	if o.BrandingProfileId.IsSet() {
		toSerialize["branding_profile_id"] = o.BrandingProfileId.Get()
	}
	return toSerialize, nil
}

func (o *DocumentCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"number",
		"issue_date",
		"currency",
		"business_profile_id",
		"customer_id",
		"line_items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDocumentCreateRequest := _DocumentCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDocumentCreateRequest)

	if err != nil {
		return err
	}

	*o = DocumentCreateRequest(varDocumentCreateRequest)

	return err
}

type NullableDocumentCreateRequest struct {
	value *DocumentCreateRequest
	isSet bool
}

func (v NullableDocumentCreateRequest) Get() *DocumentCreateRequest {
	return v.value
}

func (v *NullableDocumentCreateRequest) Set(val *DocumentCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentCreateRequest(val *DocumentCreateRequest) *NullableDocumentCreateRequest {
	return &NullableDocumentCreateRequest{value: val, isSet: true}
}

func (v NullableDocumentCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


