/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiKeyCreated type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiKeyCreated{}

// ApiKeyCreated struct for ApiKeyCreated
type ApiKeyCreated struct {
	Id string `json:"id"`
	Name string `json:"name"`
	ApiKey string `json:"api_key"`
	Last4 string `json:"last4"`
	CreatedAt string `json:"created_at"`
}

type _ApiKeyCreated ApiKeyCreated

// NewApiKeyCreated instantiates a new ApiKeyCreated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiKeyCreated(id string, name string, apiKey string, last4 string, createdAt string) *ApiKeyCreated {
	this := ApiKeyCreated{}
	this.Id = id
	this.Name = name
	this.ApiKey = apiKey
	this.Last4 = last4
	this.CreatedAt = createdAt
	return &this
}

// NewApiKeyCreatedWithDefaults instantiates a new ApiKeyCreated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiKeyCreatedWithDefaults() *ApiKeyCreated {
	this := ApiKeyCreated{}
	return &this
}

// GetId returns the Id field value
func (o *ApiKeyCreated) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApiKeyCreated) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApiKeyCreated) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ApiKeyCreated) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ApiKeyCreated) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ApiKeyCreated) SetName(v string) {
	o.Name = v
}

// GetApiKey returns the ApiKey field value
func (o *ApiKeyCreated) GetApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *ApiKeyCreated) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *ApiKeyCreated) SetApiKey(v string) {
	o.ApiKey = v
}

// GetLast4 returns the Last4 field value
func (o *ApiKeyCreated) GetLast4() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Last4
}

// GetLast4Ok returns a tuple with the Last4 field value
// and a boolean to check if the value has been set.
func (o *ApiKeyCreated) GetLast4Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Last4, true
}

// SetLast4 sets field value
func (o *ApiKeyCreated) SetLast4(v string) {
	o.Last4 = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ApiKeyCreated) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ApiKeyCreated) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ApiKeyCreated) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o ApiKeyCreated) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiKeyCreated) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["api_key"] = o.ApiKey
	toSerialize["last4"] = o.Last4
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *ApiKeyCreated) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"api_key",
		"last4",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiKeyCreated := _ApiKeyCreated{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiKeyCreated)

	if err != nil {
		return err
	}

	*o = ApiKeyCreated(varApiKeyCreated)

	return err
}

type NullableApiKeyCreated struct {
	value *ApiKeyCreated
	isSet bool
}

func (v NullableApiKeyCreated) Get() *ApiKeyCreated {
	return v.value
}

func (v *NullableApiKeyCreated) Set(val *ApiKeyCreated) {
	v.value = val
	v.isSet = true
}

func (v NullableApiKeyCreated) IsSet() bool {
	return v.isSet
}

func (v *NullableApiKeyCreated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiKeyCreated(val *ApiKeyCreated) *NullableApiKeyCreated {
	return &NullableApiKeyCreated{value: val, isSet: true}
}

func (v NullableApiKeyCreated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiKeyCreated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


