/*
InvoicePDFs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NumberingSequencePreviewResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NumberingSequencePreviewResponse{}

// NumberingSequencePreviewResponse struct for NumberingSequencePreviewResponse
type NumberingSequencePreviewResponse struct {
	Data map[string]interface{} `json:"data"`
}

type _NumberingSequencePreviewResponse NumberingSequencePreviewResponse

// NewNumberingSequencePreviewResponse instantiates a new NumberingSequencePreviewResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNumberingSequencePreviewResponse(data map[string]interface{}) *NumberingSequencePreviewResponse {
	this := NumberingSequencePreviewResponse{}
	this.Data = data
	return &this
}

// NewNumberingSequencePreviewResponseWithDefaults instantiates a new NumberingSequencePreviewResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNumberingSequencePreviewResponseWithDefaults() *NumberingSequencePreviewResponse {
	this := NumberingSequencePreviewResponse{}
	return &this
}

// GetData returns the Data field value
func (o *NumberingSequencePreviewResponse) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *NumberingSequencePreviewResponse) GetDataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *NumberingSequencePreviewResponse) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o NumberingSequencePreviewResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NumberingSequencePreviewResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *NumberingSequencePreviewResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNumberingSequencePreviewResponse := _NumberingSequencePreviewResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNumberingSequencePreviewResponse)

	if err != nil {
		return err
	}

	*o = NumberingSequencePreviewResponse(varNumberingSequencePreviewResponse)

	return err
}

type NullableNumberingSequencePreviewResponse struct {
	value *NumberingSequencePreviewResponse
	isSet bool
}

func (v NullableNumberingSequencePreviewResponse) Get() *NumberingSequencePreviewResponse {
	return v.value
}

func (v *NullableNumberingSequencePreviewResponse) Set(val *NumberingSequencePreviewResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNumberingSequencePreviewResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNumberingSequencePreviewResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNumberingSequencePreviewResponse(val *NumberingSequencePreviewResponse) *NullableNumberingSequencePreviewResponse {
	return &NullableNumberingSequencePreviewResponse{value: val, isSet: true}
}

func (v NullableNumberingSequencePreviewResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNumberingSequencePreviewResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


