/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
)

// checks if the WorkspaceMemberPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspaceMemberPatchRequest{}

// WorkspaceMemberPatchRequest struct for WorkspaceMemberPatchRequest
type WorkspaceMemberPatchRequest struct {
	Role NullableString `json:"role,omitempty"`
}

// NewWorkspaceMemberPatchRequest instantiates a new WorkspaceMemberPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspaceMemberPatchRequest() *WorkspaceMemberPatchRequest {
	this := WorkspaceMemberPatchRequest{}
	return &this
}

// NewWorkspaceMemberPatchRequestWithDefaults instantiates a new WorkspaceMemberPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspaceMemberPatchRequestWithDefaults() *WorkspaceMemberPatchRequest {
	this := WorkspaceMemberPatchRequest{}
	return &this
}

// GetRole returns the Role field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkspaceMemberPatchRequest) GetRole() string {
	if o == nil || IsNil(o.Role.Get()) {
		var ret string
		return ret
	}
	return *o.Role.Get()
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkspaceMemberPatchRequest) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Role.Get(), o.Role.IsSet()
}

// HasRole returns a boolean if a field has been set.
func (o *WorkspaceMemberPatchRequest) HasRole() bool {
	if o != nil && o.Role.IsSet() {
		return true
	}

	return false
}

// SetRole gets a reference to the given NullableString and assigns it to the Role field.
func (o *WorkspaceMemberPatchRequest) SetRole(v string) {
	o.Role.Set(&v)
}
// SetRoleNil sets the value for Role to be an explicit nil
func (o *WorkspaceMemberPatchRequest) SetRoleNil() {
	o.Role.Set(nil)
}

// UnsetRole ensures that no value is present for Role, not even an explicit nil
func (o *WorkspaceMemberPatchRequest) UnsetRole() {
	o.Role.Unset()
}

func (o WorkspaceMemberPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspaceMemberPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Role.IsSet() {
		toSerialize["role"] = o.Role.Get()
	}
	return toSerialize, nil
}

type NullableWorkspaceMemberPatchRequest struct {
	value *WorkspaceMemberPatchRequest
	isSet bool
}

func (v NullableWorkspaceMemberPatchRequest) Get() *WorkspaceMemberPatchRequest {
	return v.value
}

func (v *NullableWorkspaceMemberPatchRequest) Set(val *WorkspaceMemberPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspaceMemberPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspaceMemberPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspaceMemberPatchRequest(val *WorkspaceMemberPatchRequest) *NullableWorkspaceMemberPatchRequest {
	return &NullableWorkspaceMemberPatchRequest{value: val, isSet: true}
}

func (v NullableWorkspaceMemberPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspaceMemberPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


