/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkspaceCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspaceCreateRequest{}

// WorkspaceCreateRequest struct for WorkspaceCreateRequest
type WorkspaceCreateRequest struct {
	Name string `json:"name"`
}

type _WorkspaceCreateRequest WorkspaceCreateRequest

// NewWorkspaceCreateRequest instantiates a new WorkspaceCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspaceCreateRequest(name string) *WorkspaceCreateRequest {
	this := WorkspaceCreateRequest{}
	this.Name = name
	return &this
}

// NewWorkspaceCreateRequestWithDefaults instantiates a new WorkspaceCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspaceCreateRequestWithDefaults() *WorkspaceCreateRequest {
	this := WorkspaceCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *WorkspaceCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WorkspaceCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WorkspaceCreateRequest) SetName(v string) {
	o.Name = v
}

func (o WorkspaceCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspaceCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *WorkspaceCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkspaceCreateRequest := _WorkspaceCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkspaceCreateRequest)

	if err != nil {
		return err
	}

	*o = WorkspaceCreateRequest(varWorkspaceCreateRequest)

	return err
}

type NullableWorkspaceCreateRequest struct {
	value *WorkspaceCreateRequest
	isSet bool
}

func (v NullableWorkspaceCreateRequest) Get() *WorkspaceCreateRequest {
	return v.value
}

func (v *NullableWorkspaceCreateRequest) Set(val *WorkspaceCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspaceCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspaceCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspaceCreateRequest(val *WorkspaceCreateRequest) *NullableWorkspaceCreateRequest {
	return &NullableWorkspaceCreateRequest{value: val, isSet: true}
}

func (v NullableWorkspaceCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspaceCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


