/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StatsCounts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatsCounts{}

// StatsCounts struct for StatsCounts
type StatsCounts struct {
	Invoices int32 `json:"invoices"`
	Customers int32 `json:"customers"`
	BusinessProfiles int32 `json:"business_profiles"`
}

type _StatsCounts StatsCounts

// NewStatsCounts instantiates a new StatsCounts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatsCounts(invoices int32, customers int32, businessProfiles int32) *StatsCounts {
	this := StatsCounts{}
	this.Invoices = invoices
	this.Customers = customers
	this.BusinessProfiles = businessProfiles
	return &this
}

// NewStatsCountsWithDefaults instantiates a new StatsCounts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatsCountsWithDefaults() *StatsCounts {
	this := StatsCounts{}
	return &this
}

// GetInvoices returns the Invoices field value
func (o *StatsCounts) GetInvoices() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Invoices
}

// GetInvoicesOk returns a tuple with the Invoices field value
// and a boolean to check if the value has been set.
func (o *StatsCounts) GetInvoicesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Invoices, true
}

// SetInvoices sets field value
func (o *StatsCounts) SetInvoices(v int32) {
	o.Invoices = v
}

// GetCustomers returns the Customers field value
func (o *StatsCounts) GetCustomers() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Customers
}

// GetCustomersOk returns a tuple with the Customers field value
// and a boolean to check if the value has been set.
func (o *StatsCounts) GetCustomersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Customers, true
}

// SetCustomers sets field value
func (o *StatsCounts) SetCustomers(v int32) {
	o.Customers = v
}

// GetBusinessProfiles returns the BusinessProfiles field value
func (o *StatsCounts) GetBusinessProfiles() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BusinessProfiles
}

// GetBusinessProfilesOk returns a tuple with the BusinessProfiles field value
// and a boolean to check if the value has been set.
func (o *StatsCounts) GetBusinessProfilesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BusinessProfiles, true
}

// SetBusinessProfiles sets field value
func (o *StatsCounts) SetBusinessProfiles(v int32) {
	o.BusinessProfiles = v
}

func (o StatsCounts) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatsCounts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["invoices"] = o.Invoices
	toSerialize["customers"] = o.Customers
	toSerialize["business_profiles"] = o.BusinessProfiles
	return toSerialize, nil
}

func (o *StatsCounts) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"invoices",
		"customers",
		"business_profiles",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatsCounts := _StatsCounts{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStatsCounts)

	if err != nil {
		return err
	}

	*o = StatsCounts(varStatsCounts)

	return err
}

type NullableStatsCounts struct {
	value *StatsCounts
	isSet bool
}

func (v NullableStatsCounts) Get() *StatsCounts {
	return v.value
}

func (v *NullableStatsCounts) Set(val *StatsCounts) {
	v.value = val
	v.isSet = true
}

func (v NullableStatsCounts) IsSet() bool {
	return v.isSet
}

func (v *NullableStatsCounts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatsCounts(val *StatsCounts) *NullableStatsCounts {
	return &NullableStatsCounts{value: val, isSet: true}
}

func (v NullableStatsCounts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatsCounts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


