/*
InvoicePDFs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
)

// checks if the CreditNoteRenderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreditNoteRenderRequest{}

// CreditNoteRenderRequest struct for CreditNoteRenderRequest
type CreditNoteRenderRequest struct {
	TemplateId *string `json:"template_id,omitempty"`
	PageSize *string `json:"page_size,omitempty"`
}

// NewCreditNoteRenderRequest instantiates a new CreditNoteRenderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreditNoteRenderRequest() *CreditNoteRenderRequest {
	this := CreditNoteRenderRequest{}
	var templateId string = "tpl_modern"
	this.TemplateId = &templateId
	var pageSize string = "LETTER"
	this.PageSize = &pageSize
	return &this
}

// NewCreditNoteRenderRequestWithDefaults instantiates a new CreditNoteRenderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreditNoteRenderRequestWithDefaults() *CreditNoteRenderRequest {
	this := CreditNoteRenderRequest{}
	var templateId string = "tpl_modern"
	this.TemplateId = &templateId
	var pageSize string = "LETTER"
	this.PageSize = &pageSize
	return &this
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise.
func (o *CreditNoteRenderRequest) GetTemplateId() string {
	if o == nil || IsNil(o.TemplateId) {
		var ret string
		return ret
	}
	return *o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditNoteRenderRequest) GetTemplateIdOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateId) {
		return nil, false
	}
	return o.TemplateId, true
}

// HasTemplateId returns a boolean if a field has been set.
func (o *CreditNoteRenderRequest) HasTemplateId() bool {
	if o != nil && !IsNil(o.TemplateId) {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given string and assigns it to the TemplateId field.
func (o *CreditNoteRenderRequest) SetTemplateId(v string) {
	o.TemplateId = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *CreditNoteRenderRequest) GetPageSize() string {
	if o == nil || IsNil(o.PageSize) {
		var ret string
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreditNoteRenderRequest) GetPageSizeOk() (*string, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *CreditNoteRenderRequest) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given string and assigns it to the PageSize field.
func (o *CreditNoteRenderRequest) SetPageSize(v string) {
	o.PageSize = &v
}

func (o CreditNoteRenderRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreditNoteRenderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TemplateId) {
		toSerialize["template_id"] = o.TemplateId
	}
	if !IsNil(o.PageSize) {
		toSerialize["page_size"] = o.PageSize
	}
	return toSerialize, nil
}

type NullableCreditNoteRenderRequest struct {
	value *CreditNoteRenderRequest
	isSet bool
}

func (v NullableCreditNoteRenderRequest) Get() *CreditNoteRenderRequest {
	return v.value
}

func (v *NullableCreditNoteRenderRequest) Set(val *CreditNoteRenderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreditNoteRenderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreditNoteRenderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreditNoteRenderRequest(val *CreditNoteRenderRequest) *NullableCreditNoteRenderRequest {
	return &NullableCreditNoteRenderRequest{value: val, isSet: true}
}

func (v NullableCreditNoteRenderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreditNoteRenderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


