/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"fmt"
)

// BatchItemStatus the model 'BatchItemStatus'
type BatchItemStatus string

// List of BatchItemStatus
const (
	PENDING BatchItemStatus = "pending"
	COMPLETED BatchItemStatus = "completed"
	FAILED BatchItemStatus = "failed"
)

// All allowed values of BatchItemStatus enum
var AllowedBatchItemStatusEnumValues = []BatchItemStatus{
	"pending",
	"completed",
	"failed",
}

func (v *BatchItemStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BatchItemStatus(value)
	for _, existing := range AllowedBatchItemStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BatchItemStatus", value)
}

// NewBatchItemStatusFromValue returns a pointer to a valid BatchItemStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBatchItemStatusFromValue(v string) (*BatchItemStatus, error) {
	ev := BatchItemStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BatchItemStatus: valid values are %v", v, AllowedBatchItemStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BatchItemStatus) IsValid() bool {
	for _, existing := range AllowedBatchItemStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BatchItemStatus value
func (v BatchItemStatus) Ptr() *BatchItemStatus {
	return &v
}

type NullableBatchItemStatus struct {
	value *BatchItemStatus
	isSet bool
}

func (v NullableBatchItemStatus) Get() *BatchItemStatus {
	return v.value
}

func (v *NullableBatchItemStatus) Set(val *BatchItemStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchItemStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchItemStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchItemStatus(val *BatchItemStatus) *NullableBatchItemStatus {
	return &NullableBatchItemStatus{value: val, isSet: true}
}

func (v NullableBatchItemStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchItemStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

