/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CodeOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodeOut{}

// CodeOut struct for CodeOut
type CodeOut struct {
	Code string `json:"code"`
	Label string `json:"label"`
}

type _CodeOut CodeOut

// NewCodeOut instantiates a new CodeOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodeOut(code string, label string) *CodeOut {
	this := CodeOut{}
	this.Code = code
	this.Label = label
	return &this
}

// NewCodeOutWithDefaults instantiates a new CodeOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodeOutWithDefaults() *CodeOut {
	this := CodeOut{}
	return &this
}

// GetCode returns the Code field value
func (o *CodeOut) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *CodeOut) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *CodeOut) SetCode(v string) {
	o.Code = v
}

// GetLabel returns the Label field value
func (o *CodeOut) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *CodeOut) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *CodeOut) SetLabel(v string) {
	o.Label = v
}

func (o CodeOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodeOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["label"] = o.Label
	return toSerialize, nil
}

func (o *CodeOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"label",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCodeOut := _CodeOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCodeOut)

	if err != nil {
		return err
	}

	*o = CodeOut(varCodeOut)

	return err
}

type NullableCodeOut struct {
	value *CodeOut
	isSet bool
}

func (v NullableCodeOut) Get() *CodeOut {
	return v.value
}

func (v *NullableCodeOut) Set(val *CodeOut) {
	v.value = val
	v.isSet = true
}

func (v NullableCodeOut) IsSet() bool {
	return v.isSet
}

func (v *NullableCodeOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodeOut(val *CodeOut) *NullableCodeOut {
	return &NullableCodeOut{value: val, isSet: true}
}

func (v NullableCodeOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodeOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


