/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsageRenders type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageRenders{}

// UsageRenders struct for UsageRenders
type UsageRenders struct {
	Used int32 `json:"used"`
	Quota int32 `json:"quota"`
}

type _UsageRenders UsageRenders

// NewUsageRenders instantiates a new UsageRenders object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageRenders(used int32, quota int32) *UsageRenders {
	this := UsageRenders{}
	this.Used = used
	this.Quota = quota
	return &this
}

// NewUsageRendersWithDefaults instantiates a new UsageRenders object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageRendersWithDefaults() *UsageRenders {
	this := UsageRenders{}
	return &this
}

// GetUsed returns the Used field value
func (o *UsageRenders) GetUsed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Used
}

// GetUsedOk returns a tuple with the Used field value
// and a boolean to check if the value has been set.
func (o *UsageRenders) GetUsedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Used, true
}

// SetUsed sets field value
func (o *UsageRenders) SetUsed(v int32) {
	o.Used = v
}

// GetQuota returns the Quota field value
func (o *UsageRenders) GetQuota() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quota
}

// GetQuotaOk returns a tuple with the Quota field value
// and a boolean to check if the value has been set.
func (o *UsageRenders) GetQuotaOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quota, true
}

// SetQuota sets field value
func (o *UsageRenders) SetQuota(v int32) {
	o.Quota = v
}

func (o UsageRenders) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageRenders) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["used"] = o.Used
	toSerialize["quota"] = o.Quota
	return toSerialize, nil
}

func (o *UsageRenders) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"used",
		"quota",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsageRenders := _UsageRenders{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsageRenders)

	if err != nil {
		return err
	}

	*o = UsageRenders(varUsageRenders)

	return err
}

type NullableUsageRenders struct {
	value *UsageRenders
	isSet bool
}

func (v NullableUsageRenders) Get() *UsageRenders {
	return v.value
}

func (v *NullableUsageRenders) Set(val *UsageRenders) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageRenders) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageRenders) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageRenders(val *UsageRenders) *NullableUsageRenders {
	return &NullableUsageRenders{value: val, isSet: true}
}

func (v NullableUsageRenders) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageRenders) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


