/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
)

// checks if the WorkspacePatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspacePatchRequest{}

// WorkspacePatchRequest struct for WorkspacePatchRequest
type WorkspacePatchRequest struct {
	Name *string `json:"name,omitempty"`
}

// NewWorkspacePatchRequest instantiates a new WorkspacePatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspacePatchRequest() *WorkspacePatchRequest {
	this := WorkspacePatchRequest{}
	return &this
}

// NewWorkspacePatchRequestWithDefaults instantiates a new WorkspacePatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspacePatchRequestWithDefaults() *WorkspacePatchRequest {
	this := WorkspacePatchRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *WorkspacePatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspacePatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *WorkspacePatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *WorkspacePatchRequest) SetName(v string) {
	o.Name = &v
}

func (o WorkspacePatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspacePatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableWorkspacePatchRequest struct {
	value *WorkspacePatchRequest
	isSet bool
}

func (v NullableWorkspacePatchRequest) Get() *WorkspacePatchRequest {
	return v.value
}

func (v *NullableWorkspacePatchRequest) Set(val *WorkspacePatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspacePatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspacePatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspacePatchRequest(val *WorkspacePatchRequest) *NullableWorkspacePatchRequest {
	return &NullableWorkspacePatchRequest{value: val, isSet: true}
}

func (v NullableWorkspacePatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspacePatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


