/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TemplateVersionOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateVersionOut{}

// TemplateVersionOut struct for TemplateVersionOut
type TemplateVersionOut struct {
	Id string `json:"id"`
	TemplateId string `json:"template_id"`
	Version int32 `json:"version"`
	Label NullableString `json:"label,omitempty"`
	Changelog NullableString `json:"changelog,omitempty"`
	Config map[string]interface{} `json:"config"`
	CreatedAt string `json:"created_at"`
}

type _TemplateVersionOut TemplateVersionOut

// NewTemplateVersionOut instantiates a new TemplateVersionOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateVersionOut(id string, templateId string, version int32, config map[string]interface{}, createdAt string) *TemplateVersionOut {
	this := TemplateVersionOut{}
	this.Id = id
	this.TemplateId = templateId
	this.Version = version
	this.Config = config
	this.CreatedAt = createdAt
	return &this
}

// NewTemplateVersionOutWithDefaults instantiates a new TemplateVersionOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateVersionOutWithDefaults() *TemplateVersionOut {
	this := TemplateVersionOut{}
	return &this
}

// GetId returns the Id field value
func (o *TemplateVersionOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TemplateVersionOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TemplateVersionOut) SetId(v string) {
	o.Id = v
}

// GetTemplateId returns the TemplateId field value
func (o *TemplateVersionOut) GetTemplateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value
// and a boolean to check if the value has been set.
func (o *TemplateVersionOut) GetTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateId, true
}

// SetTemplateId sets field value
func (o *TemplateVersionOut) SetTemplateId(v string) {
	o.TemplateId = v
}

// GetVersion returns the Version field value
func (o *TemplateVersionOut) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *TemplateVersionOut) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *TemplateVersionOut) SetVersion(v int32) {
	o.Version = v
}

// GetLabel returns the Label field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TemplateVersionOut) GetLabel() string {
	if o == nil || IsNil(o.Label.Get()) {
		var ret string
		return ret
	}
	return *o.Label.Get()
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateVersionOut) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Label.Get(), o.Label.IsSet()
}

// HasLabel returns a boolean if a field has been set.
func (o *TemplateVersionOut) HasLabel() bool {
	if o != nil && o.Label.IsSet() {
		return true
	}

	return false
}

// SetLabel gets a reference to the given NullableString and assigns it to the Label field.
func (o *TemplateVersionOut) SetLabel(v string) {
	o.Label.Set(&v)
}
// SetLabelNil sets the value for Label to be an explicit nil
func (o *TemplateVersionOut) SetLabelNil() {
	o.Label.Set(nil)
}

// UnsetLabel ensures that no value is present for Label, not even an explicit nil
func (o *TemplateVersionOut) UnsetLabel() {
	o.Label.Unset()
}

// GetChangelog returns the Changelog field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TemplateVersionOut) GetChangelog() string {
	if o == nil || IsNil(o.Changelog.Get()) {
		var ret string
		return ret
	}
	return *o.Changelog.Get()
}

// GetChangelogOk returns a tuple with the Changelog field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateVersionOut) GetChangelogOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Changelog.Get(), o.Changelog.IsSet()
}

// HasChangelog returns a boolean if a field has been set.
func (o *TemplateVersionOut) HasChangelog() bool {
	if o != nil && o.Changelog.IsSet() {
		return true
	}

	return false
}

// SetChangelog gets a reference to the given NullableString and assigns it to the Changelog field.
func (o *TemplateVersionOut) SetChangelog(v string) {
	o.Changelog.Set(&v)
}
// SetChangelogNil sets the value for Changelog to be an explicit nil
func (o *TemplateVersionOut) SetChangelogNil() {
	o.Changelog.Set(nil)
}

// UnsetChangelog ensures that no value is present for Changelog, not even an explicit nil
func (o *TemplateVersionOut) UnsetChangelog() {
	o.Changelog.Unset()
}

// GetConfig returns the Config field value
func (o *TemplateVersionOut) GetConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *TemplateVersionOut) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// SetConfig sets field value
func (o *TemplateVersionOut) SetConfig(v map[string]interface{}) {
	o.Config = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *TemplateVersionOut) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *TemplateVersionOut) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *TemplateVersionOut) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o TemplateVersionOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateVersionOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["template_id"] = o.TemplateId
	toSerialize["version"] = o.Version
	if o.Label.IsSet() {
		toSerialize["label"] = o.Label.Get()
	}
	if o.Changelog.IsSet() {
		toSerialize["changelog"] = o.Changelog.Get()
	}
	toSerialize["config"] = o.Config
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *TemplateVersionOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"template_id",
		"version",
		"config",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplateVersionOut := _TemplateVersionOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplateVersionOut)

	if err != nil {
		return err
	}

	*o = TemplateVersionOut(varTemplateVersionOut)

	return err
}

type NullableTemplateVersionOut struct {
	value *TemplateVersionOut
	isSet bool
}

func (v NullableTemplateVersionOut) Get() *TemplateVersionOut {
	return v.value
}

func (v *NullableTemplateVersionOut) Set(val *TemplateVersionOut) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateVersionOut) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateVersionOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateVersionOut(val *TemplateVersionOut) *NullableTemplateVersionOut {
	return &NullableTemplateVersionOut{value: val, isSet: true}
}

func (v NullableTemplateVersionOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateVersionOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


