/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComplianceViolationOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComplianceViolationOut{}

// ComplianceViolationOut struct for ComplianceViolationOut
type ComplianceViolationOut struct {
	// The EN 16931 term or group.
	Rule string `json:"rule"`
	// Where in the document.
	Path string `json:"path"`
	Message string `json:"message"`
}

type _ComplianceViolationOut ComplianceViolationOut

// NewComplianceViolationOut instantiates a new ComplianceViolationOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComplianceViolationOut(rule string, path string, message string) *ComplianceViolationOut {
	this := ComplianceViolationOut{}
	this.Rule = rule
	this.Path = path
	this.Message = message
	return &this
}

// NewComplianceViolationOutWithDefaults instantiates a new ComplianceViolationOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComplianceViolationOutWithDefaults() *ComplianceViolationOut {
	this := ComplianceViolationOut{}
	return &this
}

// GetRule returns the Rule field value
func (o *ComplianceViolationOut) GetRule() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Rule
}

// GetRuleOk returns a tuple with the Rule field value
// and a boolean to check if the value has been set.
func (o *ComplianceViolationOut) GetRuleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rule, true
}

// SetRule sets field value
func (o *ComplianceViolationOut) SetRule(v string) {
	o.Rule = v
}

// GetPath returns the Path field value
func (o *ComplianceViolationOut) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *ComplianceViolationOut) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *ComplianceViolationOut) SetPath(v string) {
	o.Path = v
}

// GetMessage returns the Message field value
func (o *ComplianceViolationOut) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ComplianceViolationOut) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ComplianceViolationOut) SetMessage(v string) {
	o.Message = v
}

func (o ComplianceViolationOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComplianceViolationOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rule"] = o.Rule
	toSerialize["path"] = o.Path
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *ComplianceViolationOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rule",
		"path",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComplianceViolationOut := _ComplianceViolationOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComplianceViolationOut)

	if err != nil {
		return err
	}

	*o = ComplianceViolationOut(varComplianceViolationOut)

	return err
}

type NullableComplianceViolationOut struct {
	value *ComplianceViolationOut
	isSet bool
}

func (v NullableComplianceViolationOut) Get() *ComplianceViolationOut {
	return v.value
}

func (v *NullableComplianceViolationOut) Set(val *ComplianceViolationOut) {
	v.value = val
	v.isSet = true
}

func (v NullableComplianceViolationOut) IsSet() bool {
	return v.isSet
}

func (v *NullableComplianceViolationOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComplianceViolationOut(val *ComplianceViolationOut) *NullableComplianceViolationOut {
	return &NullableComplianceViolationOut{value: val, isSet: true}
}

func (v NullableComplianceViolationOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComplianceViolationOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


