/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CodeListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodeListResponse{}

// CodeListResponse A coded list from a standard, and whether it is the whole of one.  `exhaustive` is the field that changes what a client does. `true` means a value outside `data` is wrong, so the list can back a picker with no escape hatch. `false` means `data` is a shortlist of the codes an invoice usually needs — the API accepts any code, nothing validates against this, and treating it as closed rejects values that are perfectly valid.
type CodeListResponse struct {
	Data []CodeOut `json:"data"`
	// The code list these values come from.
	Standard string `json:"standard"`
	// Whether `data` is the complete list. When false it is a shortlist and other codes remain valid.
	Exhaustive bool `json:"exhaustive"`
}

type _CodeListResponse CodeListResponse

// NewCodeListResponse instantiates a new CodeListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodeListResponse(data []CodeOut, standard string, exhaustive bool) *CodeListResponse {
	this := CodeListResponse{}
	this.Data = data
	this.Standard = standard
	this.Exhaustive = exhaustive
	return &this
}

// NewCodeListResponseWithDefaults instantiates a new CodeListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodeListResponseWithDefaults() *CodeListResponse {
	this := CodeListResponse{}
	return &this
}

// GetData returns the Data field value
func (o *CodeListResponse) GetData() []CodeOut {
	if o == nil {
		var ret []CodeOut
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CodeListResponse) GetDataOk() ([]CodeOut, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *CodeListResponse) SetData(v []CodeOut) {
	o.Data = v
}

// GetStandard returns the Standard field value
func (o *CodeListResponse) GetStandard() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Standard
}

// GetStandardOk returns a tuple with the Standard field value
// and a boolean to check if the value has been set.
func (o *CodeListResponse) GetStandardOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Standard, true
}

// SetStandard sets field value
func (o *CodeListResponse) SetStandard(v string) {
	o.Standard = v
}

// GetExhaustive returns the Exhaustive field value
func (o *CodeListResponse) GetExhaustive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Exhaustive
}

// GetExhaustiveOk returns a tuple with the Exhaustive field value
// and a boolean to check if the value has been set.
func (o *CodeListResponse) GetExhaustiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Exhaustive, true
}

// SetExhaustive sets field value
func (o *CodeListResponse) SetExhaustive(v bool) {
	o.Exhaustive = v
}

func (o CodeListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodeListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["standard"] = o.Standard
	toSerialize["exhaustive"] = o.Exhaustive
	return toSerialize, nil
}

func (o *CodeListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"standard",
		"exhaustive",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCodeListResponse := _CodeListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCodeListResponse)

	if err != nil {
		return err
	}

	*o = CodeListResponse(varCodeListResponse)

	return err
}

type NullableCodeListResponse struct {
	value *CodeListResponse
	isSet bool
}

func (v NullableCodeListResponse) Get() *CodeListResponse {
	return v.value
}

func (v *NullableCodeListResponse) Set(val *CodeListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCodeListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCodeListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodeListResponse(val *CodeListResponse) *NullableCodeListResponse {
	return &NullableCodeListResponse{value: val, isSet: true}
}

func (v NullableCodeListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodeListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


