/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobOut{}

// JobOut struct for JobOut
type JobOut struct {
	Id string `json:"id"`
	Type string `json:"type"`
	Status string `json:"status"`
	Progress JobProgressOut `json:"progress"`
	Result map[string]interface{} `json:"result,omitempty"`
	Error NullableString `json:"error,omitempty"`
	CreatedAt string `json:"created_at"`
	StartedAt NullableString `json:"started_at,omitempty"`
	CompletedAt NullableString `json:"completed_at,omitempty"`
}

type _JobOut JobOut

// NewJobOut instantiates a new JobOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobOut(id string, type_ string, status string, progress JobProgressOut, createdAt string) *JobOut {
	this := JobOut{}
	this.Id = id
	this.Type = type_
	this.Status = status
	this.Progress = progress
	this.CreatedAt = createdAt
	return &this
}

// NewJobOutWithDefaults instantiates a new JobOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobOutWithDefaults() *JobOut {
	this := JobOut{}
	return &this
}

// GetId returns the Id field value
func (o *JobOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *JobOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *JobOut) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *JobOut) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *JobOut) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *JobOut) SetType(v string) {
	o.Type = v
}

// GetStatus returns the Status field value
func (o *JobOut) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *JobOut) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *JobOut) SetStatus(v string) {
	o.Status = v
}

// GetProgress returns the Progress field value
func (o *JobOut) GetProgress() JobProgressOut {
	if o == nil {
		var ret JobProgressOut
		return ret
	}

	return o.Progress
}

// GetProgressOk returns a tuple with the Progress field value
// and a boolean to check if the value has been set.
func (o *JobOut) GetProgressOk() (*JobProgressOut, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Progress, true
}

// SetProgress sets field value
func (o *JobOut) SetProgress(v JobProgressOut) {
	o.Progress = v
}

// GetResult returns the Result field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobOut) GetResult() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobOut) GetResultOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Result) {
		return map[string]interface{}{}, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *JobOut) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given map[string]interface{} and assigns it to the Result field.
func (o *JobOut) SetResult(v map[string]interface{}) {
	o.Result = v
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobOut) GetError() string {
	if o == nil || IsNil(o.Error.Get()) {
		var ret string
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobOut) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *JobOut) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableString and assigns it to the Error field.
func (o *JobOut) SetError(v string) {
	o.Error.Set(&v)
}
// SetErrorNil sets the value for Error to be an explicit nil
func (o *JobOut) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *JobOut) UnsetError() {
	o.Error.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *JobOut) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *JobOut) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *JobOut) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobOut) GetStartedAt() string {
	if o == nil || IsNil(o.StartedAt.Get()) {
		var ret string
		return ret
	}
	return *o.StartedAt.Get()
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobOut) GetStartedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartedAt.Get(), o.StartedAt.IsSet()
}

// HasStartedAt returns a boolean if a field has been set.
func (o *JobOut) HasStartedAt() bool {
	if o != nil && o.StartedAt.IsSet() {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given NullableString and assigns it to the StartedAt field.
func (o *JobOut) SetStartedAt(v string) {
	o.StartedAt.Set(&v)
}
// SetStartedAtNil sets the value for StartedAt to be an explicit nil
func (o *JobOut) SetStartedAtNil() {
	o.StartedAt.Set(nil)
}

// UnsetStartedAt ensures that no value is present for StartedAt, not even an explicit nil
func (o *JobOut) UnsetStartedAt() {
	o.StartedAt.Unset()
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobOut) GetCompletedAt() string {
	if o == nil || IsNil(o.CompletedAt.Get()) {
		var ret string
		return ret
	}
	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobOut) GetCompletedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *JobOut) HasCompletedAt() bool {
	if o != nil && o.CompletedAt.IsSet() {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given NullableString and assigns it to the CompletedAt field.
func (o *JobOut) SetCompletedAt(v string) {
	o.CompletedAt.Set(&v)
}
// SetCompletedAtNil sets the value for CompletedAt to be an explicit nil
func (o *JobOut) SetCompletedAtNil() {
	o.CompletedAt.Set(nil)
}

// UnsetCompletedAt ensures that no value is present for CompletedAt, not even an explicit nil
func (o *JobOut) UnsetCompletedAt() {
	o.CompletedAt.Unset()
}

func (o JobOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["status"] = o.Status
	toSerialize["progress"] = o.Progress
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	if o.StartedAt.IsSet() {
		toSerialize["started_at"] = o.StartedAt.Get()
	}
	if o.CompletedAt.IsSet() {
		toSerialize["completed_at"] = o.CompletedAt.Get()
	}
	return toSerialize, nil
}

func (o *JobOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"status",
		"progress",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobOut := _JobOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobOut)

	if err != nil {
		return err
	}

	*o = JobOut(varJobOut)

	return err
}

type NullableJobOut struct {
	value *JobOut
	isSet bool
}

func (v NullableJobOut) Get() *JobOut {
	return v.value
}

func (v *NullableJobOut) Set(val *JobOut) {
	v.value = val
	v.isSet = true
}

func (v NullableJobOut) IsSet() bool {
	return v.isSet
}

func (v *NullableJobOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobOut(val *JobOut) *NullableJobOut {
	return &NullableJobOut{value: val, isSet: true}
}

func (v NullableJobOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


