/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
)

// checks if the AppDocumentsSchemasDocumentRenderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppDocumentsSchemasDocumentRenderRequest{}

// AppDocumentsSchemasDocumentRenderRequest struct for AppDocumentsSchemasDocumentRenderRequest
type AppDocumentsSchemasDocumentRenderRequest struct {
	TemplateId *string `json:"template_id,omitempty"`
	PageSize *string `json:"page_size,omitempty"`
	ExpiresIn *int32 `json:"expires_in,omitempty"`
}

// NewAppDocumentsSchemasDocumentRenderRequest instantiates a new AppDocumentsSchemasDocumentRenderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppDocumentsSchemasDocumentRenderRequest() *AppDocumentsSchemasDocumentRenderRequest {
	this := AppDocumentsSchemasDocumentRenderRequest{}
	var templateId string = "tpl_modern"
	this.TemplateId = &templateId
	var pageSize string = "LETTER"
	this.PageSize = &pageSize
	var expiresIn int32 = 3600
	this.ExpiresIn = &expiresIn
	return &this
}

// NewAppDocumentsSchemasDocumentRenderRequestWithDefaults instantiates a new AppDocumentsSchemasDocumentRenderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppDocumentsSchemasDocumentRenderRequestWithDefaults() *AppDocumentsSchemasDocumentRenderRequest {
	this := AppDocumentsSchemasDocumentRenderRequest{}
	var templateId string = "tpl_modern"
	this.TemplateId = &templateId
	var pageSize string = "LETTER"
	this.PageSize = &pageSize
	var expiresIn int32 = 3600
	this.ExpiresIn = &expiresIn
	return &this
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise.
func (o *AppDocumentsSchemasDocumentRenderRequest) GetTemplateId() string {
	if o == nil || IsNil(o.TemplateId) {
		var ret string
		return ret
	}
	return *o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppDocumentsSchemasDocumentRenderRequest) GetTemplateIdOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateId) {
		return nil, false
	}
	return o.TemplateId, true
}

// HasTemplateId returns a boolean if a field has been set.
func (o *AppDocumentsSchemasDocumentRenderRequest) HasTemplateId() bool {
	if o != nil && !IsNil(o.TemplateId) {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given string and assigns it to the TemplateId field.
func (o *AppDocumentsSchemasDocumentRenderRequest) SetTemplateId(v string) {
	o.TemplateId = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *AppDocumentsSchemasDocumentRenderRequest) GetPageSize() string {
	if o == nil || IsNil(o.PageSize) {
		var ret string
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppDocumentsSchemasDocumentRenderRequest) GetPageSizeOk() (*string, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *AppDocumentsSchemasDocumentRenderRequest) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given string and assigns it to the PageSize field.
func (o *AppDocumentsSchemasDocumentRenderRequest) SetPageSize(v string) {
	o.PageSize = &v
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise.
func (o *AppDocumentsSchemasDocumentRenderRequest) GetExpiresIn() int32 {
	if o == nil || IsNil(o.ExpiresIn) {
		var ret int32
		return ret
	}
	return *o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppDocumentsSchemasDocumentRenderRequest) GetExpiresInOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpiresIn) {
		return nil, false
	}
	return o.ExpiresIn, true
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *AppDocumentsSchemasDocumentRenderRequest) HasExpiresIn() bool {
	if o != nil && !IsNil(o.ExpiresIn) {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given int32 and assigns it to the ExpiresIn field.
func (o *AppDocumentsSchemasDocumentRenderRequest) SetExpiresIn(v int32) {
	o.ExpiresIn = &v
}

func (o AppDocumentsSchemasDocumentRenderRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppDocumentsSchemasDocumentRenderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TemplateId) {
		toSerialize["template_id"] = o.TemplateId
	}
	if !IsNil(o.PageSize) {
		toSerialize["page_size"] = o.PageSize
	}
	if !IsNil(o.ExpiresIn) {
		toSerialize["expires_in"] = o.ExpiresIn
	}
	return toSerialize, nil
}

type NullableAppDocumentsSchemasDocumentRenderRequest struct {
	value *AppDocumentsSchemasDocumentRenderRequest
	isSet bool
}

func (v NullableAppDocumentsSchemasDocumentRenderRequest) Get() *AppDocumentsSchemasDocumentRenderRequest {
	return v.value
}

func (v *NullableAppDocumentsSchemasDocumentRenderRequest) Set(val *AppDocumentsSchemasDocumentRenderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAppDocumentsSchemasDocumentRenderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAppDocumentsSchemasDocumentRenderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppDocumentsSchemasDocumentRenderRequest(val *AppDocumentsSchemasDocumentRenderRequest) *NullableAppDocumentsSchemasDocumentRenderRequest {
	return &NullableAppDocumentsSchemasDocumentRenderRequest{value: val, isSet: true}
}

func (v NullableAppDocumentsSchemasDocumentRenderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppDocumentsSchemasDocumentRenderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


