/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"fmt"
)

// RecurringInvoiceStatus Where a recurring schedule is in its life.  `completed` is the schedule running out, not a failure: it is set automatically once the end date or the occurrence count is reached.
type RecurringInvoiceStatus string

// List of RecurringInvoiceStatus
const (
	ACTIVE RecurringInvoiceStatus = "active"
	PAUSED RecurringInvoiceStatus = "paused"
	CANCELLED RecurringInvoiceStatus = "cancelled"
	COMPLETED RecurringInvoiceStatus = "completed"
)

// All allowed values of RecurringInvoiceStatus enum
var AllowedRecurringInvoiceStatusEnumValues = []RecurringInvoiceStatus{
	"active",
	"paused",
	"cancelled",
	"completed",
}

func (v *RecurringInvoiceStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RecurringInvoiceStatus(value)
	for _, existing := range AllowedRecurringInvoiceStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RecurringInvoiceStatus", value)
}

// NewRecurringInvoiceStatusFromValue returns a pointer to a valid RecurringInvoiceStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRecurringInvoiceStatusFromValue(v string) (*RecurringInvoiceStatus, error) {
	ev := RecurringInvoiceStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RecurringInvoiceStatus: valid values are %v", v, AllowedRecurringInvoiceStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RecurringInvoiceStatus) IsValid() bool {
	for _, existing := range AllowedRecurringInvoiceStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RecurringInvoiceStatus value
func (v RecurringInvoiceStatus) Ptr() *RecurringInvoiceStatus {
	return &v
}

type NullableRecurringInvoiceStatus struct {
	value *RecurringInvoiceStatus
	isSet bool
}

func (v NullableRecurringInvoiceStatus) Get() *RecurringInvoiceStatus {
	return v.value
}

func (v *NullableRecurringInvoiceStatus) Set(val *RecurringInvoiceStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableRecurringInvoiceStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableRecurringInvoiceStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecurringInvoiceStatus(val *RecurringInvoiceStatus) *NullableRecurringInvoiceStatus {
	return &NullableRecurringInvoiceStatus{value: val, isSet: true}
}

func (v NullableRecurringInvoiceStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecurringInvoiceStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

