/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TimezoneOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimezoneOut{}

// TimezoneOut struct for TimezoneOut
type TimezoneOut struct {
	Name string `json:"name"`
	Offset string `json:"offset"`
}

type _TimezoneOut TimezoneOut

// NewTimezoneOut instantiates a new TimezoneOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimezoneOut(name string, offset string) *TimezoneOut {
	this := TimezoneOut{}
	this.Name = name
	this.Offset = offset
	return &this
}

// NewTimezoneOutWithDefaults instantiates a new TimezoneOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimezoneOutWithDefaults() *TimezoneOut {
	this := TimezoneOut{}
	return &this
}

// GetName returns the Name field value
func (o *TimezoneOut) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TimezoneOut) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TimezoneOut) SetName(v string) {
	o.Name = v
}

// GetOffset returns the Offset field value
func (o *TimezoneOut) GetOffset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *TimezoneOut) GetOffsetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *TimezoneOut) SetOffset(v string) {
	o.Offset = v
}

func (o TimezoneOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimezoneOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["offset"] = o.Offset
	return toSerialize, nil
}

func (o *TimezoneOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"offset",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTimezoneOut := _TimezoneOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTimezoneOut)

	if err != nil {
		return err
	}

	*o = TimezoneOut(varTimezoneOut)

	return err
}

type NullableTimezoneOut struct {
	value *TimezoneOut
	isSet bool
}

func (v NullableTimezoneOut) Get() *TimezoneOut {
	return v.value
}

func (v *NullableTimezoneOut) Set(val *TimezoneOut) {
	v.value = val
	v.isSet = true
}

func (v NullableTimezoneOut) IsSet() bool {
	return v.isSet
}

func (v *NullableTimezoneOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimezoneOut(val *TimezoneOut) *NullableTimezoneOut {
	return &NullableTimezoneOut{value: val, isSet: true}
}

func (v NullableTimezoneOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimezoneOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


