/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RenderOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RenderOut{}

// RenderOut struct for RenderOut
type RenderOut struct {
	Id string `json:"id"`
	Status string `json:"status"`
	DocumentType string `json:"document_type"`
	Format string `json:"format"`
	DownloadUrl string `json:"download_url"`
	ExpiresAt string `json:"expires_at"`
	Calculation CalculationBreakdown `json:"calculation"`
	CreatedAt string `json:"created_at"`
}

type _RenderOut RenderOut

// NewRenderOut instantiates a new RenderOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRenderOut(id string, status string, documentType string, format string, downloadUrl string, expiresAt string, calculation CalculationBreakdown, createdAt string) *RenderOut {
	this := RenderOut{}
	this.Id = id
	this.Status = status
	this.DocumentType = documentType
	this.Format = format
	this.DownloadUrl = downloadUrl
	this.ExpiresAt = expiresAt
	this.Calculation = calculation
	this.CreatedAt = createdAt
	return &this
}

// NewRenderOutWithDefaults instantiates a new RenderOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRenderOutWithDefaults() *RenderOut {
	this := RenderOut{}
	return &this
}

// GetId returns the Id field value
func (o *RenderOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RenderOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RenderOut) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *RenderOut) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *RenderOut) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *RenderOut) SetStatus(v string) {
	o.Status = v
}

// GetDocumentType returns the DocumentType field value
func (o *RenderOut) GetDocumentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocumentType
}

// GetDocumentTypeOk returns a tuple with the DocumentType field value
// and a boolean to check if the value has been set.
func (o *RenderOut) GetDocumentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentType, true
}

// SetDocumentType sets field value
func (o *RenderOut) SetDocumentType(v string) {
	o.DocumentType = v
}

// GetFormat returns the Format field value
func (o *RenderOut) GetFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Format
}

// GetFormatOk returns a tuple with the Format field value
// and a boolean to check if the value has been set.
func (o *RenderOut) GetFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Format, true
}

// SetFormat sets field value
func (o *RenderOut) SetFormat(v string) {
	o.Format = v
}

// GetDownloadUrl returns the DownloadUrl field value
func (o *RenderOut) GetDownloadUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DownloadUrl
}

// GetDownloadUrlOk returns a tuple with the DownloadUrl field value
// and a boolean to check if the value has been set.
func (o *RenderOut) GetDownloadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DownloadUrl, true
}

// SetDownloadUrl sets field value
func (o *RenderOut) SetDownloadUrl(v string) {
	o.DownloadUrl = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *RenderOut) GetExpiresAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *RenderOut) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *RenderOut) SetExpiresAt(v string) {
	o.ExpiresAt = v
}

// GetCalculation returns the Calculation field value
func (o *RenderOut) GetCalculation() CalculationBreakdown {
	if o == nil {
		var ret CalculationBreakdown
		return ret
	}

	return o.Calculation
}

// GetCalculationOk returns a tuple with the Calculation field value
// and a boolean to check if the value has been set.
func (o *RenderOut) GetCalculationOk() (*CalculationBreakdown, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Calculation, true
}

// SetCalculation sets field value
func (o *RenderOut) SetCalculation(v CalculationBreakdown) {
	o.Calculation = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *RenderOut) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *RenderOut) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *RenderOut) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o RenderOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RenderOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["document_type"] = o.DocumentType
	toSerialize["format"] = o.Format
	toSerialize["download_url"] = o.DownloadUrl
	toSerialize["expires_at"] = o.ExpiresAt
	toSerialize["calculation"] = o.Calculation
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *RenderOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"document_type",
		"format",
		"download_url",
		"expires_at",
		"calculation",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRenderOut := _RenderOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRenderOut)

	if err != nil {
		return err
	}

	*o = RenderOut(varRenderOut)

	return err
}

type NullableRenderOut struct {
	value *RenderOut
	isSet bool
}

func (v NullableRenderOut) Get() *RenderOut {
	return v.value
}

func (v *NullableRenderOut) Set(val *RenderOut) {
	v.value = val
	v.isSet = true
}

func (v NullableRenderOut) IsSet() bool {
	return v.isSet
}

func (v *NullableRenderOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRenderOut(val *RenderOut) *NullableRenderOut {
	return &NullableRenderOut{value: val, isSet: true}
}

func (v NullableRenderOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRenderOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


