/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BrandingProfileOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BrandingProfileOut{}

// BrandingProfileOut struct for BrandingProfileOut
type BrandingProfileOut struct {
	Id string `json:"id"`
	Name string `json:"name"`
	IsDefault bool `json:"is_default"`
	LogoFileId NullableString `json:"logo_file_id,omitempty"`
	PrimaryColor string `json:"primary_color"`
	AccentColor string `json:"accent_color"`
	FontFamily NullableString `json:"font_family,omitempty"`
	HeaderText NullableString `json:"header_text,omitempty"`
	FooterText string `json:"footer_text"`
	HideInvoicepdfsBranding bool `json:"hide_invoicepdfs_branding"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type _BrandingProfileOut BrandingProfileOut

// NewBrandingProfileOut instantiates a new BrandingProfileOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBrandingProfileOut(id string, name string, isDefault bool, primaryColor string, accentColor string, footerText string, hideInvoicepdfsBranding bool, createdAt string, updatedAt string) *BrandingProfileOut {
	this := BrandingProfileOut{}
	this.Id = id
	this.Name = name
	this.IsDefault = isDefault
	this.PrimaryColor = primaryColor
	this.AccentColor = accentColor
	this.FooterText = footerText
	this.HideInvoicepdfsBranding = hideInvoicepdfsBranding
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewBrandingProfileOutWithDefaults instantiates a new BrandingProfileOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBrandingProfileOutWithDefaults() *BrandingProfileOut {
	this := BrandingProfileOut{}
	return &this
}

// GetId returns the Id field value
func (o *BrandingProfileOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BrandingProfileOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BrandingProfileOut) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *BrandingProfileOut) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BrandingProfileOut) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BrandingProfileOut) SetName(v string) {
	o.Name = v
}

// GetIsDefault returns the IsDefault field value
func (o *BrandingProfileOut) GetIsDefault() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value
// and a boolean to check if the value has been set.
func (o *BrandingProfileOut) GetIsDefaultOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsDefault, true
}

// SetIsDefault sets field value
func (o *BrandingProfileOut) SetIsDefault(v bool) {
	o.IsDefault = v
}

// GetLogoFileId returns the LogoFileId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BrandingProfileOut) GetLogoFileId() string {
	if o == nil || IsNil(o.LogoFileId.Get()) {
		var ret string
		return ret
	}
	return *o.LogoFileId.Get()
}

// GetLogoFileIdOk returns a tuple with the LogoFileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BrandingProfileOut) GetLogoFileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogoFileId.Get(), o.LogoFileId.IsSet()
}

// HasLogoFileId returns a boolean if a field has been set.
func (o *BrandingProfileOut) HasLogoFileId() bool {
	if o != nil && o.LogoFileId.IsSet() {
		return true
	}

	return false
}

// SetLogoFileId gets a reference to the given NullableString and assigns it to the LogoFileId field.
func (o *BrandingProfileOut) SetLogoFileId(v string) {
	o.LogoFileId.Set(&v)
}
// SetLogoFileIdNil sets the value for LogoFileId to be an explicit nil
func (o *BrandingProfileOut) SetLogoFileIdNil() {
	o.LogoFileId.Set(nil)
}

// UnsetLogoFileId ensures that no value is present for LogoFileId, not even an explicit nil
func (o *BrandingProfileOut) UnsetLogoFileId() {
	o.LogoFileId.Unset()
}

// GetPrimaryColor returns the PrimaryColor field value
func (o *BrandingProfileOut) GetPrimaryColor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrimaryColor
}

// GetPrimaryColorOk returns a tuple with the PrimaryColor field value
// and a boolean to check if the value has been set.
func (o *BrandingProfileOut) GetPrimaryColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrimaryColor, true
}

// SetPrimaryColor sets field value
func (o *BrandingProfileOut) SetPrimaryColor(v string) {
	o.PrimaryColor = v
}

// GetAccentColor returns the AccentColor field value
func (o *BrandingProfileOut) GetAccentColor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccentColor
}

// GetAccentColorOk returns a tuple with the AccentColor field value
// and a boolean to check if the value has been set.
func (o *BrandingProfileOut) GetAccentColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccentColor, true
}

// SetAccentColor sets field value
func (o *BrandingProfileOut) SetAccentColor(v string) {
	o.AccentColor = v
}

// GetFontFamily returns the FontFamily field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BrandingProfileOut) GetFontFamily() string {
	if o == nil || IsNil(o.FontFamily.Get()) {
		var ret string
		return ret
	}
	return *o.FontFamily.Get()
}

// GetFontFamilyOk returns a tuple with the FontFamily field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BrandingProfileOut) GetFontFamilyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FontFamily.Get(), o.FontFamily.IsSet()
}

// HasFontFamily returns a boolean if a field has been set.
func (o *BrandingProfileOut) HasFontFamily() bool {
	if o != nil && o.FontFamily.IsSet() {
		return true
	}

	return false
}

// SetFontFamily gets a reference to the given NullableString and assigns it to the FontFamily field.
func (o *BrandingProfileOut) SetFontFamily(v string) {
	o.FontFamily.Set(&v)
}
// SetFontFamilyNil sets the value for FontFamily to be an explicit nil
func (o *BrandingProfileOut) SetFontFamilyNil() {
	o.FontFamily.Set(nil)
}

// UnsetFontFamily ensures that no value is present for FontFamily, not even an explicit nil
func (o *BrandingProfileOut) UnsetFontFamily() {
	o.FontFamily.Unset()
}

// GetHeaderText returns the HeaderText field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BrandingProfileOut) GetHeaderText() string {
	if o == nil || IsNil(o.HeaderText.Get()) {
		var ret string
		return ret
	}
	return *o.HeaderText.Get()
}

// GetHeaderTextOk returns a tuple with the HeaderText field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BrandingProfileOut) GetHeaderTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HeaderText.Get(), o.HeaderText.IsSet()
}

// HasHeaderText returns a boolean if a field has been set.
func (o *BrandingProfileOut) HasHeaderText() bool {
	if o != nil && o.HeaderText.IsSet() {
		return true
	}

	return false
}

// SetHeaderText gets a reference to the given NullableString and assigns it to the HeaderText field.
func (o *BrandingProfileOut) SetHeaderText(v string) {
	o.HeaderText.Set(&v)
}
// SetHeaderTextNil sets the value for HeaderText to be an explicit nil
func (o *BrandingProfileOut) SetHeaderTextNil() {
	o.HeaderText.Set(nil)
}

// UnsetHeaderText ensures that no value is present for HeaderText, not even an explicit nil
func (o *BrandingProfileOut) UnsetHeaderText() {
	o.HeaderText.Unset()
}

// GetFooterText returns the FooterText field value
func (o *BrandingProfileOut) GetFooterText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FooterText
}

// GetFooterTextOk returns a tuple with the FooterText field value
// and a boolean to check if the value has been set.
func (o *BrandingProfileOut) GetFooterTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FooterText, true
}

// SetFooterText sets field value
func (o *BrandingProfileOut) SetFooterText(v string) {
	o.FooterText = v
}

// GetHideInvoicepdfsBranding returns the HideInvoicepdfsBranding field value
func (o *BrandingProfileOut) GetHideInvoicepdfsBranding() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HideInvoicepdfsBranding
}

// GetHideInvoicepdfsBrandingOk returns a tuple with the HideInvoicepdfsBranding field value
// and a boolean to check if the value has been set.
func (o *BrandingProfileOut) GetHideInvoicepdfsBrandingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HideInvoicepdfsBranding, true
}

// SetHideInvoicepdfsBranding sets field value
func (o *BrandingProfileOut) SetHideInvoicepdfsBranding(v bool) {
	o.HideInvoicepdfsBranding = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *BrandingProfileOut) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *BrandingProfileOut) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *BrandingProfileOut) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *BrandingProfileOut) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *BrandingProfileOut) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *BrandingProfileOut) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o BrandingProfileOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BrandingProfileOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["is_default"] = o.IsDefault
	if o.LogoFileId.IsSet() {
		toSerialize["logo_file_id"] = o.LogoFileId.Get()
	}
	toSerialize["primary_color"] = o.PrimaryColor
	toSerialize["accent_color"] = o.AccentColor
	if o.FontFamily.IsSet() {
		toSerialize["font_family"] = o.FontFamily.Get()
	}
	if o.HeaderText.IsSet() {
		toSerialize["header_text"] = o.HeaderText.Get()
	}
	toSerialize["footer_text"] = o.FooterText
	toSerialize["hide_invoicepdfs_branding"] = o.HideInvoicepdfsBranding
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *BrandingProfileOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"is_default",
		"primary_color",
		"accent_color",
		"footer_text",
		"hide_invoicepdfs_branding",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBrandingProfileOut := _BrandingProfileOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBrandingProfileOut)

	if err != nil {
		return err
	}

	*o = BrandingProfileOut(varBrandingProfileOut)

	return err
}

type NullableBrandingProfileOut struct {
	value *BrandingProfileOut
	isSet bool
}

func (v NullableBrandingProfileOut) Get() *BrandingProfileOut {
	return v.value
}

func (v *NullableBrandingProfileOut) Set(val *BrandingProfileOut) {
	v.value = val
	v.isSet = true
}

func (v NullableBrandingProfileOut) IsSet() bool {
	return v.isSet
}

func (v *NullableBrandingProfileOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBrandingProfileOut(val *BrandingProfileOut) *NullableBrandingProfileOut {
	return &NullableBrandingProfileOut{value: val, isSet: true}
}

func (v NullableBrandingProfileOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBrandingProfileOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


