/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BillingSubscriptionData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingSubscriptionData{}

// BillingSubscriptionData struct for BillingSubscriptionData
type BillingSubscriptionData struct {
	SubscriptionId NullableString `json:"subscription_id,omitempty"`
	Status NullableString `json:"status,omitempty"`
	PlanId string `json:"plan_id"`
	PlanName string `json:"plan_name"`
}

type _BillingSubscriptionData BillingSubscriptionData

// NewBillingSubscriptionData instantiates a new BillingSubscriptionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingSubscriptionData(planId string, planName string) *BillingSubscriptionData {
	this := BillingSubscriptionData{}
	this.PlanId = planId
	this.PlanName = planName
	return &this
}

// NewBillingSubscriptionDataWithDefaults instantiates a new BillingSubscriptionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingSubscriptionDataWithDefaults() *BillingSubscriptionData {
	this := BillingSubscriptionData{}
	return &this
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BillingSubscriptionData) GetSubscriptionId() string {
	if o == nil || IsNil(o.SubscriptionId.Get()) {
		var ret string
		return ret
	}
	return *o.SubscriptionId.Get()
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BillingSubscriptionData) GetSubscriptionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubscriptionId.Get(), o.SubscriptionId.IsSet()
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *BillingSubscriptionData) HasSubscriptionId() bool {
	if o != nil && o.SubscriptionId.IsSet() {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given NullableString and assigns it to the SubscriptionId field.
func (o *BillingSubscriptionData) SetSubscriptionId(v string) {
	o.SubscriptionId.Set(&v)
}
// SetSubscriptionIdNil sets the value for SubscriptionId to be an explicit nil
func (o *BillingSubscriptionData) SetSubscriptionIdNil() {
	o.SubscriptionId.Set(nil)
}

// UnsetSubscriptionId ensures that no value is present for SubscriptionId, not even an explicit nil
func (o *BillingSubscriptionData) UnsetSubscriptionId() {
	o.SubscriptionId.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BillingSubscriptionData) GetStatus() string {
	if o == nil || IsNil(o.Status.Get()) {
		var ret string
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BillingSubscriptionData) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *BillingSubscriptionData) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableString and assigns it to the Status field.
func (o *BillingSubscriptionData) SetStatus(v string) {
	o.Status.Set(&v)
}
// SetStatusNil sets the value for Status to be an explicit nil
func (o *BillingSubscriptionData) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *BillingSubscriptionData) UnsetStatus() {
	o.Status.Unset()
}

// GetPlanId returns the PlanId field value
func (o *BillingSubscriptionData) GetPlanId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value
// and a boolean to check if the value has been set.
func (o *BillingSubscriptionData) GetPlanIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanId, true
}

// SetPlanId sets field value
func (o *BillingSubscriptionData) SetPlanId(v string) {
	o.PlanId = v
}

// GetPlanName returns the PlanName field value
func (o *BillingSubscriptionData) GetPlanName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlanName
}

// GetPlanNameOk returns a tuple with the PlanName field value
// and a boolean to check if the value has been set.
func (o *BillingSubscriptionData) GetPlanNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanName, true
}

// SetPlanName sets field value
func (o *BillingSubscriptionData) SetPlanName(v string) {
	o.PlanName = v
}

func (o BillingSubscriptionData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingSubscriptionData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.SubscriptionId.IsSet() {
		toSerialize["subscription_id"] = o.SubscriptionId.Get()
	}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	toSerialize["plan_id"] = o.PlanId
	toSerialize["plan_name"] = o.PlanName
	return toSerialize, nil
}

func (o *BillingSubscriptionData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plan_id",
		"plan_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingSubscriptionData := _BillingSubscriptionData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillingSubscriptionData)

	if err != nil {
		return err
	}

	*o = BillingSubscriptionData(varBillingSubscriptionData)

	return err
}

type NullableBillingSubscriptionData struct {
	value *BillingSubscriptionData
	isSet bool
}

func (v NullableBillingSubscriptionData) Get() *BillingSubscriptionData {
	return v.value
}

func (v *NullableBillingSubscriptionData) Set(val *BillingSubscriptionData) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingSubscriptionData) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingSubscriptionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingSubscriptionData(val *BillingSubscriptionData) *NullableBillingSubscriptionData {
	return &NullableBillingSubscriptionData{value: val, isSet: true}
}

func (v NullableBillingSubscriptionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingSubscriptionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


