/*
InvoicePDFs

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreditNoteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreditNoteResponse{}

// CreditNoteResponse struct for CreditNoteResponse
type CreditNoteResponse struct {
	Data CreditNoteOut `json:"data"`
}

type _CreditNoteResponse CreditNoteResponse

// NewCreditNoteResponse instantiates a new CreditNoteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreditNoteResponse(data CreditNoteOut) *CreditNoteResponse {
	this := CreditNoteResponse{}
	this.Data = data
	return &this
}

// NewCreditNoteResponseWithDefaults instantiates a new CreditNoteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreditNoteResponseWithDefaults() *CreditNoteResponse {
	this := CreditNoteResponse{}
	return &this
}

// GetData returns the Data field value
func (o *CreditNoteResponse) GetData() CreditNoteOut {
	if o == nil {
		var ret CreditNoteOut
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreditNoteResponse) GetDataOk() (*CreditNoteOut, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreditNoteResponse) SetData(v CreditNoteOut) {
	o.Data = v
}

func (o CreditNoteResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreditNoteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreditNoteResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreditNoteResponse := _CreditNoteResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreditNoteResponse)

	if err != nil {
		return err
	}

	*o = CreditNoteResponse(varCreditNoteResponse)

	return err
}

type NullableCreditNoteResponse struct {
	value *CreditNoteResponse
	isSet bool
}

func (v NullableCreditNoteResponse) Get() *CreditNoteResponse {
	return v.value
}

func (v *NullableCreditNoteResponse) Set(val *CreditNoteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreditNoteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreditNoteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreditNoteResponse(val *CreditNoteResponse) *NullableCreditNoteResponse {
	return &NullableCreditNoteResponse{value: val, isSet: true}
}

func (v NullableCreditNoteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreditNoteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


