/*
InvoicePDFs

InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package invoicepdfs

import (
	"encoding/json"
)

// checks if the TaxRatePatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaxRatePatchRequest{}

// TaxRatePatchRequest struct for TaxRatePatchRequest
type TaxRatePatchRequest struct {
	Name NullableString `json:"name,omitempty"`
	Rate NullableString `json:"rate,omitempty"`
	Inclusive NullableBool `json:"inclusive,omitempty"`
	Jurisdiction NullableString `json:"jurisdiction,omitempty"`
	IsActive NullableBool `json:"is_active,omitempty"`
}

// NewTaxRatePatchRequest instantiates a new TaxRatePatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaxRatePatchRequest() *TaxRatePatchRequest {
	this := TaxRatePatchRequest{}
	return &this
}

// NewTaxRatePatchRequestWithDefaults instantiates a new TaxRatePatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaxRatePatchRequestWithDefaults() *TaxRatePatchRequest {
	this := TaxRatePatchRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TaxRatePatchRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaxRatePatchRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *TaxRatePatchRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *TaxRatePatchRequest) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *TaxRatePatchRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *TaxRatePatchRequest) UnsetName() {
	o.Name.Unset()
}

// GetRate returns the Rate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TaxRatePatchRequest) GetRate() string {
	if o == nil || IsNil(o.Rate.Get()) {
		var ret string
		return ret
	}
	return *o.Rate.Get()
}

// GetRateOk returns a tuple with the Rate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaxRatePatchRequest) GetRateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rate.Get(), o.Rate.IsSet()
}

// HasRate returns a boolean if a field has been set.
func (o *TaxRatePatchRequest) HasRate() bool {
	if o != nil && o.Rate.IsSet() {
		return true
	}

	return false
}

// SetRate gets a reference to the given NullableString and assigns it to the Rate field.
func (o *TaxRatePatchRequest) SetRate(v string) {
	o.Rate.Set(&v)
}
// SetRateNil sets the value for Rate to be an explicit nil
func (o *TaxRatePatchRequest) SetRateNil() {
	o.Rate.Set(nil)
}

// UnsetRate ensures that no value is present for Rate, not even an explicit nil
func (o *TaxRatePatchRequest) UnsetRate() {
	o.Rate.Unset()
}

// GetInclusive returns the Inclusive field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TaxRatePatchRequest) GetInclusive() bool {
	if o == nil || IsNil(o.Inclusive.Get()) {
		var ret bool
		return ret
	}
	return *o.Inclusive.Get()
}

// GetInclusiveOk returns a tuple with the Inclusive field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaxRatePatchRequest) GetInclusiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Inclusive.Get(), o.Inclusive.IsSet()
}

// HasInclusive returns a boolean if a field has been set.
func (o *TaxRatePatchRequest) HasInclusive() bool {
	if o != nil && o.Inclusive.IsSet() {
		return true
	}

	return false
}

// SetInclusive gets a reference to the given NullableBool and assigns it to the Inclusive field.
func (o *TaxRatePatchRequest) SetInclusive(v bool) {
	o.Inclusive.Set(&v)
}
// SetInclusiveNil sets the value for Inclusive to be an explicit nil
func (o *TaxRatePatchRequest) SetInclusiveNil() {
	o.Inclusive.Set(nil)
}

// UnsetInclusive ensures that no value is present for Inclusive, not even an explicit nil
func (o *TaxRatePatchRequest) UnsetInclusive() {
	o.Inclusive.Unset()
}

// GetJurisdiction returns the Jurisdiction field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TaxRatePatchRequest) GetJurisdiction() string {
	if o == nil || IsNil(o.Jurisdiction.Get()) {
		var ret string
		return ret
	}
	return *o.Jurisdiction.Get()
}

// GetJurisdictionOk returns a tuple with the Jurisdiction field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaxRatePatchRequest) GetJurisdictionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Jurisdiction.Get(), o.Jurisdiction.IsSet()
}

// HasJurisdiction returns a boolean if a field has been set.
func (o *TaxRatePatchRequest) HasJurisdiction() bool {
	if o != nil && o.Jurisdiction.IsSet() {
		return true
	}

	return false
}

// SetJurisdiction gets a reference to the given NullableString and assigns it to the Jurisdiction field.
func (o *TaxRatePatchRequest) SetJurisdiction(v string) {
	o.Jurisdiction.Set(&v)
}
// SetJurisdictionNil sets the value for Jurisdiction to be an explicit nil
func (o *TaxRatePatchRequest) SetJurisdictionNil() {
	o.Jurisdiction.Set(nil)
}

// UnsetJurisdiction ensures that no value is present for Jurisdiction, not even an explicit nil
func (o *TaxRatePatchRequest) UnsetJurisdiction() {
	o.Jurisdiction.Unset()
}

// GetIsActive returns the IsActive field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TaxRatePatchRequest) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive.Get()) {
		var ret bool
		return ret
	}
	return *o.IsActive.Get()
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TaxRatePatchRequest) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsActive.Get(), o.IsActive.IsSet()
}

// HasIsActive returns a boolean if a field has been set.
func (o *TaxRatePatchRequest) HasIsActive() bool {
	if o != nil && o.IsActive.IsSet() {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given NullableBool and assigns it to the IsActive field.
func (o *TaxRatePatchRequest) SetIsActive(v bool) {
	o.IsActive.Set(&v)
}
// SetIsActiveNil sets the value for IsActive to be an explicit nil
func (o *TaxRatePatchRequest) SetIsActiveNil() {
	o.IsActive.Set(nil)
}

// UnsetIsActive ensures that no value is present for IsActive, not even an explicit nil
func (o *TaxRatePatchRequest) UnsetIsActive() {
	o.IsActive.Unset()
}

func (o TaxRatePatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaxRatePatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Rate.IsSet() {
		toSerialize["rate"] = o.Rate.Get()
	}
	if o.Inclusive.IsSet() {
		toSerialize["inclusive"] = o.Inclusive.Get()
	}
	if o.Jurisdiction.IsSet() {
		toSerialize["jurisdiction"] = o.Jurisdiction.Get()
	}
	if o.IsActive.IsSet() {
		toSerialize["is_active"] = o.IsActive.Get()
	}
	return toSerialize, nil
}

type NullableTaxRatePatchRequest struct {
	value *TaxRatePatchRequest
	isSet bool
}

func (v NullableTaxRatePatchRequest) Get() *TaxRatePatchRequest {
	return v.value
}

func (v *NullableTaxRatePatchRequest) Set(val *TaxRatePatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTaxRatePatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTaxRatePatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaxRatePatchRequest(val *TaxRatePatchRequest) *NullableTaxRatePatchRequest {
	return &NullableTaxRatePatchRequest{value: val, isSet: true}
}

func (v NullableTaxRatePatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaxRatePatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


